### ISSUE TITLE
Error occurs.  'python3 train_SemanticKitti.py'

### ISSUE THREAD

**Issue by kxhit** [HuguesTHOMAS/KPConv-PyTorch#1]
Hi! Thanks for implementing the pytorch version!

I met some error when I run  'python3 train_SemanticKitti.py'.
My environment is ubuntu16.04, python=3.5, pytorch=1.2.0, cuda=10.0.
Could you give me some suggestions for that? Thanks!

Logs are below:

```
 python train_SemanticKitti.py 

Data Preparation
****************
Preparing seq 00 class frames. (Long but one time only)
Preparing seq 01 class frames. (Long but one time only)
Preparing seq 02 class frames. (Long but one time only)
Preparing seq 03 class frames. (Long but one time only)
Preparing seq 04 class frames. (Long but one time only)
Preparing seq 05 class frames. (Long but one time only)
Preparing seq 06 class frames. (Long but one time only)
Preparing seq 07 class frames. (Long but one time only)
Preparing seq 09 class frames. (Long but one time only)
Preparing seq 10 class frames. (Long but one time only)
Preparing seq 08 class frames. (Long but one time only)

Starting Calibration of max_in_points value (use verbose=True for more details)

Previous calibration found:
Check max_in limit dictionary
"balanced_6.000_0.060": ?
Traceback (most recent call last):
  File "train_SemanticKitti.py", line 290, in <module>
    training_sampler.calib_max_in(config, training_loader, verbose=True)
  File "/media/work/3D/KPConv-PyTorch/datasets/SemanticKitti.py", line 904, in calib_max_in
    for batch_i, batch in enumerate(dataloader):
  File "/home/kx/venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kx/venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/home/kx/venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/home/kx/venv/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self.sampler_iter)  # may raise StopIteration
  File "/home/kx/venv/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/media/work/3D/KPConv-PyTorch/datasets/SemanticKitti.py", line 780, in __iter__
    self.dataset.potentials[class_indices] += np.random.rand(class_indices.shape[0]) * 0.1 + 0.1
TypeError: add_(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```

**Comment by HuguesTHOMAS** [comment]
Hi @kxhit,

Thanks for spotting this mistake, this should corrected now. Tell me if you encounter any other error.

**Comment by kxhit** [comment]
Thanks for your response!

New error occurs:

```
python train_SemanticKitti.py 

Data Preparation
****************

Starting Calibration of max_in_points value (use verbose=True for more details)

Previous calibration found:
Check max_in limit dictionary
"balanced_6.000_0.060": ?
Traceback (most recent call last):
  File "train_SemanticKitti.py", line 290, in <module>
    training_sampler.calib_max_in(config, training_loader, verbose=True)
  File "/media/work/3D/KPConv-PyTorch/datasets/SemanticKitti.py", line 907, in calib_max_in
    all_lengths += batch.lengths[0]
TypeError: add(): argument 'other' (position 1) must be Tensor, not list

```

**Comment by HuguesTHOMAS** [comment]
Mmmh, I think I know what is the problem here.

The last mistake was a problem of automatic conversion from np.array to Tensors, and here again from tensors to list.
I assume in my PyTorch version (1.4), the conversion is handled, while it was not in your older version.

I just fixed this particular line by adding a .tolist(). But you might encounter other errors of this type. If you do, pleas let me know here so that I can fix the implementation for you, and anyone who needs to use older version of PyTorch
Thx!

**Comment by kxhit** [comment]
Thanks! I can successfully run this.
However, I got `CUDA out of memory` error even with batch=1 `    # Number of batch
    batch_num = 1 # 8
    val_batch_num = 1`. It can be trained for a while and will dump at validation. How much GPU memory is needed? My GPU is TITAN XP with 12G GPU memory. 

Logs are below:
`Start training
**************
e000-i0003 => L=2.895 acc= 10% / t(ms):   8.7  39.3  23.3)
e000-i0020 => L=1.821 acc= 40% / t(ms):   1.8  32.4  27.1)
e000-i0038 => L=1.826 acc= 27% / t(ms):   0.6  32.6  29.7)
e000-i0056 => L=1.928 acc= 52% / t(ms):   0.5  29.9  26.6)
e000-i0075 => L=2.334 acc= 14% / t(ms):   0.4  29.7  24.5)
e000-i0091 => L=1.271 acc= 69% / t(ms):   0.4  32.7  30.6)
e000-i0108 => L=1.439 acc= 36% / t(ms):   0.4  31.1  27.4)
e000-i0126 => L=1.916 acc= 46% / t(ms):   0.4  31.4  26.7)
e000-i0144 => L=0.994 acc= 80% / t(ms):   0.4  31.6  27.8)
e000-i0163 => L=2.062 acc= 45% / t(ms):   0.4  26.7  24.0)
e000-i0181 => L=2.437 acc= 23% / t(ms):   0.4  30.8  24.6)
e000-i0199 => L=2.912 acc= 13% / t(ms):   0.3  29.7  26.7)
e000-i0214 => L=1.449 acc= 22% / t(ms):   0.9  37.5  29.9)
e000-i0230 => L=1.391 acc= 71% / t(ms):   0.5  34.3  29.3)
e000-i0247 => L=1.681 acc= 48% / t(ms):   0.5  32.4  27.6)
e000-i0266 => L=2.437 acc= 25% / t(ms):   0.4  29.8  25.4)
e000-i0284 => L=1.535 acc= 51% / t(ms):   0.4  32.8  28.9)
e000-i0301 => L=2.251 acc= 23% / t(ms):   0.4  31.3  28.3)
e000-i0319 => L=1.263 acc= 75% / t(ms):   0.4  31.4  26.3)
e000-i0334 => L=3.072 acc=  8% / t(ms):   0.5  35.2  29.0)
e000-i0352 => L=1.527 acc= 61% / t(ms):   0.4  31.9  27.7)
e000-i0371 => L=2.072 acc=  4% / t(ms):   0.4  29.4  25.8)
e000-i0389 => L=1.284 acc= 37% / t(ms):   0.4  31.5  28.7)
e000-i0408 => L=1.688 acc= 55% / t(ms):   0.4  29.1  24.4)
e000-i0426 => L=1.368 acc= 73% / t(ms):   0.4  33.1  27.6)
e000-i0444 => L=1.548 acc= 28% / t(ms):   0.5  30.1  25.5)
e000-i0462 => L=2.758 acc= 11% / t(ms):   0.5  30.7  25.3)
e000-i0479 => L=2.269 acc= 32% / t(ms):   0.5  32.3  29.1)
e000-i0498 => L=1.875 acc= 35% / t(ms):   0.3  27.7  25.4)
Validation : 0.0% (timings : 231.78 24.25)
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 247, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "train_SemanticKitti.py", line 328, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "/media/work/3D/KPConv-PyTorch/utils/trainer.py", line 271, in train
    self.validation(net, val_loader, config)
  File "/media/work/3D/KPConv-PyTorch/utils/trainer.py", line 289, in validation
    self.slam_segmentation_validation(net, val_loader, config)
  File "/media/work/3D/KPConv-PyTorch/utils/trainer.py", line 709, in slam_segmentation_validation
    outputs = net(batch, config)
  File "/home/kx/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/work/3D/KPConv-PyTorch/models/architectures.py", line 332, in forward
    x = block_op(x, batch)
  File "/home/kx/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/work/3D/KPConv-PyTorch/models/blocks.py", line 635, in forward
    x = self.KPConv(q_pts, s_pts, neighb_inds, x)
  File "/home/kx/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/work/3D/KPConv-PyTorch/models/blocks.py", line 370, in forward
    kernel_outputs = torch.matmul(weighted_features, self.weights)
RuntimeError: CUDA out of memory. Tried to allocate 202.00 MiB (GPU 0; 11.91 GiB total capacity; 10.16 GiB already allocated; 61.81 MiB free; 594.90 MiB cached)
`

**Comment by antonyvan** [comment]
Hi, Hugues and kxhit,
I also met  kxhit's memory issu.  I found you set  val_radius = 51.0.
val_radius is too big ? is this a typo? 
Thanks

**Comment by HuguesTHOMAS** [comment]
Hi guys, 

Happy to hear the code runs now. About the memory issue here are some details. The important parameters for memory (in addition to the depth of the architecture) are defined here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/ccb820bbb7a18e4642c317bc8a80d26164f7f3c1/train_SemanticKitti.py#L98-L107

Smaller input radius means less input points, so you save memory. If you don't want to reduce the radius you can also use a higher `first_subsampling_dl` which will have the same effect. The input radius can be different for validation for two reasons:
 1. During training, having a smaller input radius and the balanced_class=True means the network will "see" minority classes more often
 2. During validation, having `val_radius=51.0` means you predict all the frame, which is better if your GPU can handle it. Otherwise the part of the frame that is predicted is chosen randomly, so some points of the whole dataset will likely never be tested (you will still have a decent estimation of the overall performances though).
To answer @antonyvan, you don't really need to use the same radius for validation and training. Performance-wise, the ideal setup is a small in_radius and `val_radius=51.0` like I had before. The only op that could be affected by this change is the batch_norm, but it does not seem to create problems though.

I also wanted to mention  `max_in_points` and `max_val_points` which can be used to limit the number of points in a batch. If the batch have more points, we randomly drop some of them. That could be helpful if you want to try to keep `val_radius=51.0` . But if you end up dropping too many points, maybe you should consider just increasing `first_subsampling_dl` 

N.B. I just reduced the depth of the architecture and changed the values of these parameters to have something that should fit in 12GB GPUs.

**Comment by kxhit** [comment]
Hi! @HuguesTHOMAS  Thanks for your help. With your updated code, I can successfully run now and it takes me about 8000MB GPU memory. Cheers! 

I'm curious of the best performance parameter settings. Mine is still training and the results at 195 epochs are below.

` mean | car   bicy  moto  truc  othe  pers  bicy  moto  road  park  side  othe  buil  fenc  vege  trun  terr  pole  traf 
------|------------------------------------------------------------------------------------------------------------------------
 53.5 | 92.4  23.1  46.9  35.8  32.9  65.2  78.2  10.1  85.1  18.3  70.4  0.7   87.6  55.5  86.0  69.0  71.1  57.9  31.2 
------|------------------------------------------------------------------------------------------------------------------------
 47.9 | 90.7  15.0  31.7  20.4  34.1  51.5  61.9  0.2   83.1  18.1  66.8  0.3   83.9  52.6  85.1  60.1  70.7  58.0  26.2 
`

**Comment by HuguesTHOMAS** [comment]
@kxhit,

I wrote this code for SemanticKitti after KPConv Paper, so I did not spend a lot of time testing the parameters. You can try to submit results on the official benchmark to see how you compare to my own previous results and to the best current methods. The only problem will be to ensure that you really test all the points of the test scenes if you cannot set 'val_radius=51.0'. I should look into that in the next week, but if you come with your own idea for it, you can share it here.

Best, Hugues

**Comment by tangbohu** [comment]
> Hi! @HuguesTHOMAS Thanks for your help. With your updated code, I can successfully run now and it takes me about 8000MB GPU memory. Cheers!
> 
> I'm curious of the best performance parameter settings. Mine is still training and the results at 195 epochs are below.
> 
> ` mean	car bicy moto truc othe pers bicy moto road park side othe buil fenc vege trun terr pole traf
> 53.5	92.4 23.1 46.9 35.8 32.9 65.2 78.2 10.1 85.1 18.3 70.4 0.7 87.6 55.5 86.0 69.0 71.1 57.9 31.2
> ------	------------------------------------------------------------------------------------------------------------------------
> 47.9	90.7 15.0 31.7 20.4 34.1 51.5 61.9 0.2 83.1 18.1 66.8 0.3 83.9 52.6 85.1 60.1 70.7 58.0 26.2
> `

Hi! Have you got the final performance? Would you mind sharing your final results on the validation and the test set? Thanks!
