### ISSUE TITLE
Data Input format

### ISSUE THREAD

**Issue by GeondoPark** [HuguesTHOMAS/KPConv-PyTorch#10]
Thank you for releasing your PyTorch code.  It`s awesome and nice work.
I have a question about the flow of this code.

In my knowledge, for the s3dis dataset, the input format of the network would be (Batch x Points x 3+RGB). 
But, I understand why the last dimension in the input list 3~5. 
But, can I ask you why your first dimension of the input list is 103955?
When I see the input of kpconv, the input have the (103955, 5)  dimension. 

Sorry for bothering you due to my short knowledge.

**Comment by HuguesTHOMAS** [comment]
You can find clarifications on how we handle batch dimensions here https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/6#issuecomment-626848054

The dimensions of the features is 5 because we use 1 + RGB + height, that makes 5 channels
