### ISSUE TITLE
how many points semantic segmentation model consumes?

### ISSUE THREAD

**Issue by pixar0407** [HuguesTHOMAS/KPConv-PyTorch#103]
Hi, @HuguesTHOMAS 

just a quick question!
1) How many points semantic segmantation and part segmentation model consumes?

2) And for the semantic segmentation, does decoder layer use three-nn operation?
I don't see any three-nn operation. And I see that you use pre-computed neighbor information. So, which means that you don't use three-nn and use radius search for decoder layers?

3) In your phd thesis, you said that grid sampling is efficient than farthest point sampling because of FPS's compute complexity. How about replacing the grid sampling with FPS? does it reduce the accuracy of model? 

Thank you.

**Comment by HuguesTHOMAS** [comment]
Hi @pixar0407,

1. The number of points consumed is variable. You can find more details in the paper in particular on TAble three of the supplementary material.

2. Decoder uses a nearest-neighbor interpolation, see the upsampling layer: 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/1cd3742fc57e5ba9d21f7909c78a05a971781351/models/blocks.py#L664

3. I did not compare the subsampling strategies, but I would say the performances should be the same

Best,
Hugues
