### ISSUE TITLE
memory limit ? 

### ISSUE THREAD

**Issue by berwingan** [HuguesTHOMAS/KPConv-PyTorch#105]
Is there a minimum memory limit required for the GPUs? I tried training without changing any of the code on the S3DIS dataset and usually get an error after the 2nd or 3rd step. Usually something like this. 

RuntimeError: CUDA out of memory. Tried to allocate 4.11 GiB (GPU 0; 10.91 GiB total capacity; 6.00 GiB already allocated; 256.38 MiB free; 10.14 GiB reserved in total by PyTorch)

**Comment by HuguesTHOMAS** [comment]
See previous issues #24
