### ISSUE TITLE
The ScanNet dataset

### ISSUE THREAD

**Issue by zwy1996** [HuguesTHOMAS/KPConv-PyTorch#108]
Hello, nice job!

I was sorry to bother you abount scannet dataset. I have noticed the result 68.4 miou in the scannet, Because of the version of scannet, I want to know more about this, which version(v1 or v2) did you use? How much memory needs to be consumed？ And another supporting documents？such as train/val split. 

I will very appreciate if you can offer the dataloader of scannet and train_net.py

best wishs to you!

**Comment by HuguesTHOMAS** [comment]
I used the scannet v2 dataset. The one used for their [online benchmark](http://kaldir.vc.in.tum.de/scannet_benchmark/). Train/val splits are the usual ones. I am sorry, but I have not implemented this in PyTorch.

**Comment by zwy1996** [comment]
ok, I got it. thanks for your reply!

Thank you very much!
