### ISSUE TITLE
How to repeat S3DIS results tested by Area-5 in this paper?

### ISSUE THREAD

**Issue by whuhxb** [HuguesTHOMAS/KPConv-PyTorch#114]
Hi,
   Now, I can't repeat the results of S3DIS tested by Area-5 in paper. Now my parameter setting is as below. I use in_radius=1.5 to obtain the test_models.py results of mIoU about 32. How to set the parameters for S3DIS to obtain the results reported in paper? Thanks a lot.

# -----------------------------------#
# Parameters of the training session #
# -----------------------------------#

# Input parameters
# ****************

dataset = S3DIS
dataset_task = cloud_segmentation
num_classes = 13
in_points_dim = 3
in_features_dim = 5
in_radius = 1.500000
input_threads = 10

# Model parameters
# ****************

architecture = simple resnetb resnetb_strided resnetb resnetb resnetb_strided resnetb_deformable resnetb_deformable resnetb_deformable_strided resnetb_deformable resnetb_deformable resnetb_deformable_strided resnetb_deformable resnetb_deformable nearest_upsample unary nearest_upsample unary nearest_upsample unary nearest_upsample unary
equivar_mode = 
invar_mode = 
num_layers = 5
first_features_dim = 128
use_batch_norm = 1
batch_norm_momentum = 0.020000

segmentation_ratio = 1.000000

# KPConv parameters
# *****************

first_subsampling_dl = 0.050000
num_kernel_points = 15
conv_radius = 2.500000
deform_radius = 6.000000
fixed_kernel_points = center
KP_extent = 1.200000
KP_influence = linear
aggregation_mode = sum
modulated = 0
n_frames = 1
max_in_points = 0

max_val_points = 50000

val_radius = 51.000000

**Comment by zhangzihui247** [comment]
Hi, Xiaobing, 

I find you asked the setting of hypter-parameters to reproduce the performance on S3DIS.
So, have you got that? I'm also seeking values of these parameters. If you found, could tell me? 

thanks,
zihui
