### ISSUE TITLE
KPConv model size

### ISSUE THREAD

**Issue by edshkim98** [HuguesTHOMAS/KPConv-PyTorch#120]
Dear author,

I am interested in the space and time complexities of KPConv, but I couldn't find metrics such as GMAC in the paper.
Would you be able to provide this information?
Thank you!

**Comment by HuguesTHOMAS** [comment]
Sorry I don't have that information.

The space and time complexity is hard to evaluate because it is not fixed. It depends on several parameters including the density of the input data, the variable batch size etc

Best,
Hugues
