### ISSUE TITLE
Testing my own dataset with pretrained model

### ISSUE THREAD

**Issue by Alanyg7** [HuguesTHOMAS/KPConv-PyTorch#126]
Hi Hugues,

I really admire your work and truly thank you for sharing your achievements here! I downloaded your pretrained model and test it with S3DIS dataset. The result looks pretty excellent to me!
Now I would like to try one of my own collected dataset, which is a indoor room scene made by laser scanners. I have the raw point cloud and corresponding points location and RGB information in a txt file. And now I would like to test the pretrained model on this dataset.
What I do is I put this point cloud and name it as Area_7 append to S3DIS dataset to save some work, however I cannot get the predicted classes showing on my point cloud. May I know if my method to achieve the task is wrong and how I can properly solve my issue?

Thanks a lot for your help!
Alan

**Comment by HuguesTHOMAS** [comment]
Hi @Alanyg7,

Thank you for your kind words, I am happy that you like my work. 

Your idea is excellent, it will save you the trouble of creating a new dataset class. However, you have to be sure that your data is in the same format as the S3DIS dataset. You need to save it as a binary ply file in the folder `original_ply` with the same property names as the one I used for s3dis. Here is the line that can do that in my code:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/73e444d486cd6cb56122c3dd410e51c734064cfe/datasets/S3DIS.py#L688-L691

When that is done, You need to go check the code in S3DIS dataset class init method here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/73e444d486cd6cb56122c3dd410e51c734064cfe/datasets/S3DIS.py#L112-L115

- Add Area_7 to the list of names
- Add a new split to the list of splits. Use `6` if you want your area to be tested alone or `4` if you still want Area_5 to be tested with it.
- Choose the split that will be tested, so 6 or 4 depending on how you defined your splits

That should do the trick. Good luck with your project,
Best,
Hugues

**Comment by Alanyg7** [comment]
Hi Hugues,

Really thank you for answering my issue with detailed code explanation!
I will try it with my project!

Thanks a lot!
Alan
