### ISSUE TITLE
Difference between in_radius and conv_radius

### ISSUE THREAD

**Issue by michaelzhou0723** [HuguesTHOMAS/KPConv-PyTorch#13]
Hi, could you please clarify the meaning of in_radius and conv_radius in the config class? If I understand correctly, conv_radius is the spherical domain of kernel function g.  But it should be the same as the neighbourhood radius of each input point.

Thanks in advance!

**Comment by HuguesTHOMAS** [comment]
You are right, conv radius is the spherical domain of the kernel function g, which is the same as the neighborhood radius  of each input points.

The parameter in_radius controls the radius of the big shere which contain all the input points fed to the network.

**Comment by michaelzhou0723** [comment]
> You are right, conv radius is the spherical domain of the kernel function g, which is the same as the neighborhood radius of each input points.
> 
> The parameter in_radius controls the radius of the big shere which contain all the input points fed to the network.

Is the unit of in_radius in meters?

**Comment by HuguesTHOMAS** [comment]
Yes exactly
