### ISSUE TITLE
Performance of KPConv on S3DIS

### ISSUE THREAD

**Issue by guochengqian** [HuguesTHOMAS/KPConv-PyTorch#14]
Hi, @HuguesTHOMAS 
Thanks for your amazing work. 
I wonder could this PyTorch code (seg on S3DIS) reproduce the results in the paper? 

Thank you.

**Comment by HuguesTHOMAS** [comment]
Hi @guochengqian,

Thanx for your interest.

Yes it can. Actually I even reach better performaces on Pytorch (but mainly because I am using bigger GPUs now and therefore deeper network architectures).

Best,
Hugues

**Comment by guochengqian** [comment]
> Hi @guochengqian,
> 
> Thanx for your interest.
> 
> Yes it can. Actually I even reach better performaces on Pytorch (but mainly because I am using bigger GPUs now and therefore deeper network architectures).
> 
> Best,
> Hugues

Great! Thank you.

**Comment by whuhxb** [comment]
Hi, 
   What's the parameter settings for S3DID of KPConv to reproduce the results reported in the paper? I set radius_in=1.5, first_subsampling_dl = 0.04, and batch_num=3, but the final Confusion on full point clouds is only mIoU about 32, not about 64. I want to reproduce the results of S3DIS? Could you please share the parameter settings? Thanks a lot.
