### ISSUE TITLE
ERROR: It seems that the calibration have not reached convergence. Here are some plot to understand why:

### ISSUE THREAD

**Issue by luzonghao1** [HuguesTHOMAS/KPConv-PyTorch#144]
**I did not modify other parameter，except the dataset path. When use python train_S3DIS.py,it will have this prolem.**

python train_S3DIS.py

Data Preparation
****************

Preparing ply files
Done in 0.0s

Found KDTree for cloud Area_1, subsampled at 0.030
146.6 MB loaded in 26.0s

Found KDTree for cloud Area_2, subsampled at 0.030
159.1 MB loaded in 16.7s

Found KDTree for cloud Area_3, subsampled at 0.030
62.6 MB loaded in 8.8s

Found KDTree for cloud Area_4, subsampled at 0.030
144.2 MB loaded in 13.2s

Found KDTree for cloud Area_6, subsampled at 0.030
137.9 MB loaded in 8.1s

Preparing potentials
Done in 0.0s

Preparing ply files
Done in 0.0s

Found KDTree for cloud Area_5, subsampled at 0.030
260.4 MB loaded in 28.8s

Preparing potentials
Done in 0.0s

Preparing reprojection indices for testing
Area_5 done in 1.0s

Starting Calibration (use verbose=True for more details)

Previous calibration found:
Check batch limit dictionary
"potentials_1.200_0.030_6": 40760
Check neighbors limit dictionary
"0.030_0.075": 28
"0.060_0.150": 31
"0.120_0.300": 38
"0.240_1.200": ?
"0.480_2.400": ?
Step     1  estim_b = 0.05 batch_limit =  43760
Step     2  estim_b = 0.09 batch_limit =  47262
Step     4  estim_b = 0.19 batch_limit =  48266
Step     6  estim_b = 0.30 batch_limit =  43271
Step    11  estim_b = 0.52 batch_limit =  46293
Step    14  estim_b = 0.66 batch_limit =  47813
Step    15  estim_b = 0.70 batch_limit =  50821
Step    16  estim_b = 0.74 batch_limit =  51329
Step    21  estim_b = 1.00 batch_limit =  46370
Step    25  estim_b = 1.19 batch_limit =  49404
Step    26  estim_b = 1.25 batch_limit =  46412
Step    29  estim_b = 1.39 batch_limit =  46436
Step    36  estim_b = 1.71 batch_limit =  48489
Step    39  estim_b = 1.86 batch_limit =  42511
Step    46  estim_b = 2.19 batch_limit =  45044
ERROR: It seems that the calibration have not reached convergence. Here are some plot to understand why:
If you notice unstability, reduce the expected_N value
If convergece is too slow, increase the expected_N value

![1643204086(1)](https://user-images.githubusercontent.com/11958034/151172423-5f4a4269-4bb7-4218-8542-40813b7a7fce.png)
![1643204099(1)](https://user-images.githubusercontent.com/11958034/151172447-04ca94d3-7750-4908-a868-c7128f99ef15.png)

I did not modify otherparameter，except the dataset path. When use python train_S3DIS.py,it will have this.

**Comment by HuguesTHOMAS** [comment]
Mmmmh this error seems very strange... Could you please go here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/73e444d486cd6cb56122c3dd410e51c734064cfe/datasets/S3DIS.py#L1195-L1203

and print the values of self.N before the loop and the value of batch_i inside the loop. 

I suspect that the `dataloader` yields only one example at each epoch.

**Comment by luzonghao1** [comment]
Thank you very much for your prompt reply. Since you say the error is strange. It's maybe my fault. I just reclone the code,then it's fine.

**Comment by Yarroudh** [comment]
I got the same error while trying to train on my own data:

```
ERROR: It seems that the calibration have not reached convergence. Here are some plot to understand why:
If you notice unstability, reduce the expected_N value
If convergece is too slow, increase the expected_N value
```

![Figure_1](https://github.com/HuguesTHOMAS/KPConv-PyTorch/assets/72500344/77fd20e0-8916-47f3-976c-e1c5442c2711)

![Figure_2](https://github.com/HuguesTHOMAS/KPConv-PyTorch/assets/72500344/fa3b87c2-8cbd-4018-ab46-d7477336a09d)
