### ISSUE TITLE
A bug appears when running my own dataset

### ISSUE THREAD

**Issue by BruceWayne233** [HuguesTHOMAS/KPConv-PyTorch#149]
Hello mr.Thomas.Thank you for your wonderful work.I have some question.
I use your recommand radius and first_sub_sampling value,it's useful for my work,however,a bug appears when running my own dataset
![image](https://user-images.githubusercontent.com/44676054/156550505-c1818fcd-098b-48bb-b62b-96691679c268.png)
when  I continue the previous training path to train the model, it shows:
![image](https://user-images.githubusercontent.com/44676054/156550659-fe77d957-57a0-4420-9f46-a9a3d495ccb3.png)
This is the first time I have this problem，could please give some advice？

Good luck to all！

**Comment by HuguesTHOMAS** [comment]
Hi @BruceWayne233,

It seems you are trying to load a configuration file from a previous trained model, and it seems to be invalid.

The first question is: did you make any modification to the file [utils/config.py](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/utils/config.py)?

If yes then change it back to the original. 

If not (which is more likely), you may have modified a value from one parameter in the file [train_S3DIS.py](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/train_S3DIS.py), which should be an integer type and set it to 3.0 instead of 3.

**Comment by BruceWayne233** [comment]
Hello Mr.Thomas. Thanks for your help， I should set radius = 3.0 rather than 3. When I set the radius = 3.0, I've never had a similar problem again. But sometimes this question occurs.
![image](https://user-images.githubusercontent.com/44676054/156684237-79210551-25ff-4951-bd8a-c8d6fd46bc10.png)
I guess it 's because I don 't have enough gpu capacity ?
Good luck to all！

**Comment by BruceWayne233** [comment]
Hello Mr.Thomas，I 'm sorry to bother you.
There's another problem occur when I try to use the test_model
![image](https://user-images.githubusercontent.com/44676054/156690664-a71593e9-98da-4075-bbcd-c85d1131cfad.png)
By the way, I'd like to know how can I make sure the test_radius is equal to the train radius? Where can I set the config of test?
Thank you for your patient guidance and kindness

**Comment by BruceWayne233** [comment]
Hello Mr.Thomas，I have fixed the problem. I didn ' t train enough epochs, so it casue this silly mistake.
Now I 've got another problem right now.
 I remember the last time you said that New area5.ply files will be saved every 50 epochs with the current validation results.
But I didn't find it. Now I see this problem.
![image](https://user-images.githubusercontent.com/44676054/156746694-9adec1bb-6537-467f-9284-19e313a5cea1.png)
why I can't save the cloud?Please help me,it's my honor to get your advice.
Thank you for your generous share as always.

**Comment by HuguesTHOMAS** [comment]
it seems like there is a problem of dimension when you are trying to save the pointcloud. 

This happens here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/e600c1667d085aeb5cf89d8dbe5a97aad4270d88/utils/tester.py#L426-L445

can you try to print `points.shape` and `preds.shape` to see what is the problem in the dimensions?

**Comment by BruceWayne233** [comment]
Hi Mr.Thomas, Thank you for your sincere advice.
I've try to print the points.shape and preds.shape,here's result
![image](https://user-images.githubusercontent.com/44676054/156879990-ef529a5e-b87a-46ce-920f-a185df1ff3e5.png)
it seems like the points.shape is not equal to the pred.shape
Is this situation normal？
By the way , there is my dataset. It consists two class——ground and non_ground.
Could give me some advice?
Thank you for your generous share as always.

**Comment by HuguesTHOMAS** [comment]
Ok so you can take a look at the code that leads to this:

`preds` comes from `proj_probs` which is the result probabilities returned by the network, projected from the subsampled point clouds (precomputed for the network) to the original data points here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/e600c1667d085aeb5cf89d8dbe5a97aad4270d88/utils/tester.py#L360-L370

the `test_loader.dataset.test_proj` are the projection indices, computed in advance during data preprocessing.




The points are the original data points loaded from the original file: https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/e600c1667d085aeb5cf89d8dbe5a97aad4270d88/utils/tester.py#L420-L421.

I'll let you investigate which one is the mistake. I would say the points are given that there are fewer of them, but that is just a hunch.

**Comment by BruceWayne233** [comment]
Thank you for your generous share as always!
In my opinion , I have to make sure the number of points equals to the number of preds, so that I can fix this problem. Am I right?
And there are some blank in my test data

Is this gonna effect the result or lead to some bug?
Good luck to all!

**Comment by BruceWayne233** [comment]
I don't know why I can not update the picture of my test data, I will update it as soon as it could

**Comment by HuguesTHOMAS** [comment]
> I have to make sure the number of points equals to the number of press

yes. It seems to me that you do not load the same point cloud that is used as input for your network

**Comment by BruceWayne233** [comment]
Hello sir. Today when I running the test program, I've encounter an mistake.

Traceback (most recent call last):
  File "D:/kp-2022-04-6/KPConv-PyTorch-master/test_models.py", line 214, in <module>
    tester.cloud_segmentation_test(net, test_loader, config)
  File "D:\kp-2022-04-6\KPConv-PyTorch-master\utils\tester.py", line 240, in cloud_segmentation_test
    for i, batch in enumerate(test_loader):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\kp-2022-04-6\KPConv-PyTorch-master\datasets\S3DIS.py", line 238, in __getitem__
    return self.potential_item(batch_i)
  File "D:\kp-2022-04-6\KPConv-PyTorch-master\datasets\S3DIS.py", line 348, in potential_item
    raise ValueError('It seems this dataset only containes empty input spheres')
ValueError: It seems this dataset only containes empty input spheres

Now I am using the s3dis dataset,
Could give me some advice?
Thank you for your generous share as always.

**Comment by BruceWayne233** [comment]
Another quick question. The predict ply file will be saved after several times of predict on the full point cloud, and the final predict result will be saved in for example in test/Light_KPFCNN/prediction.
Am I understand correct? If there's some mistake, please let me know.
By the way, I really think I should try to test the result in Linux, I think it's window10 may make me encouter these question,like the wrong filed dimmensions, and some broken pip question.

**Comment by HuguesTHOMAS** [comment]
> ValueError: It seems this dataset only contains empty input spheres

This first error comes from a recent update that I made especially for people trying to use the method on their own dataset. It means that when trying to load input spheres into a batch, the code encountered a lot of empty spheres (containing a single point in the center). These inputs are ignored because they are useless, and they create bugs in the pipeline, but I still have this safety check that indicates that your dataset does not seem very good because it has a lot of isolated points that probably should be filtered out.

If you don't want to change your dataset, you can just stop this error from happening by changing the line 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/7255680ff05bdce1ba29d15a3f5ab272cb7de18d/datasets/S3DIS.py#L347

Put some very high value like `1e6` instead of 100 and you should be good to go.

> Another quick question. The predict ply file will be saved after several times of predict on the full point cloud, and the final predict result will be saved in for example in test/Light_KPFCNN/prediction.
Am I understand correct? If there's some mistake, please let me know.

This sounds about right. YOu can modify the tester code to have this saved quicker if you want

> By the way, I really think I should try to test the result in Linux, I think it's window10 may make me encouter these question,like the wrong filed dimmensions, and some broken pip question.

Indeed, I personally use and test this code on Linux, so you would not have as many issues if you migrate from Windows

**Comment by BruceWayne233** [comment]
Thank you for your careful and patient response.I will try the code on Linux.
I'd like try to add a new layers to the network，what should I do? 
My understand is: First, I need create my layer in the block.py
                             Second, I need to change the architectures.py
                             At last, I have to change the  architecture in the train_s3dis.py
Am I understand correct? If there's some mistake, please let me know.

**Comment by HuguesTHOMAS** [comment]
Yes that is correct

**Comment by BruceWayne233** [comment]
Thank you sir!

**Comment by BruceWayne233** [comment]
Hello Dr.Thomas
Thanks for your help, I finally find out why I have the wrong dimensions.I've run this code under the windows 10, which use the '\' to split the directory, for example: .\data\s3dis, but under the linux it use the '/' to splie the directory， so I mixed them together,that's why I couldn't get the correct result.Thanks for your help, it's my mistake.
I have a another question, I noticed that 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/utils/tester.py#L448
It seems like that I need to set the test_loader.dataset.set to the test so that it can save the result in txt.
could I just add these
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/utils/tester.py#L452
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/utils/tester.py#L453
could I just add these under the 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/utils/tester.py#L445
or I should change the validation to test in this place?
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/cf1f06381ef062344b68286e3d5034b1aa94aecd/test_models.py#L170
Thanks for your help!

**Comment by HuguesTHOMAS** [comment]
If you need to have results saved in a text file, I would say the easiest is to place allow the saving command when you are in validation. So yo can replace 

```python
if test_loader.dataset.set == 'test': 
```

by 
```python
if test_loader.dataset.set in ['test', 'validation']: 
```

here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/utils/tester.py#L447-L453

**Comment by BruceWayne233** [comment]
Thank you sir!
