### ISSUE TITLE
About S3DIS

### ISSUE THREAD

**Issue by GeoSur** [HuguesTHOMAS/KPConv-PyTorch#152]
Thank alot for your sharing!! I have a question to ask.
As i konw s3dis contains 13 labes, but why the S3DIS.py contains only 12 label names?  "stairs" label is not named?

**Comment by HuguesTHOMAS** [comment]
There are 13 labels listed:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/e600c1667d085aeb5cf89d8dbe5a97aad4270d88/datasets/S3DIS.py#L68-L80

Stairs is not a label for this dataset
