### ISSUE TITLE
About the net architecture

### ISSUE THREAD

**Issue by BruceWayne233** [HuguesTHOMAS/KPConv-PyTorch#161]
Hello Dr Thomas
I noticed that in your paper, the encoder of rigid KPFCNN has five layers. Each layer contains two convolutional blocks.And in your pytorch version, it seems like there are three convolution blocks in the first four layers.
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/train_S3DIS.py#L93-L114
The 1th-4th layers seems composed with  kpconv, kpconv, kpconv-stride
The fifth layers coposed with kpconv kpconv
The kpconv I reference this one
![image](https://user-images.githubusercontent.com/44676054/164895959-46ca76a9-2b8b-485d-a26d-02e4b9db8b53.png)

Does the pytorch version different with the paper version?  Does my understand correct?
Thank you for your help!

**Comment by BruceWayne233** [comment]
Hello Dr.Thomas
I've got some questions and I really need your help.
I try to explore the out shape of each block(only in the encoder).
I add this after the line332
` print("current_block:", block_i, "current_shape", x.shape)`
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/architectures.py#L329-L332
Here is the result:
current_block: 0 current_shape torch.Size([15641, 64])
current_block: 1 current_shape torch.Size([15641, 128])
current_block: 2 current_shape torch.Size([8635, 128])
current_block: 3 current_shape torch.Size([8635, 256])
current_block: 4 current_shape torch.Size([8635, 256])
current_block: 5 current_shape torch.Size([3361, 256])
current_block: 6 current_shape torch.Size([3361, 512])
current_block: 7 current_shape torch.Size([3361, 512])
current_block: 8 current_shape torch.Size([940, 512])
current_block: 9 current_shape torch.Size([940, 1024])
current_block: 10 current_shape torch.Size([940, 1024])
current_block: 11 current_shape torch.Size([239, 1024])
current_block: 12 current_shape torch.Size([239, 2048])
current_block: 13 current_shape torch.Size([239, 2048])
I have some questions about the result. In my opinion, for example, the shape is [239,2048], 239 is the number of points in this batch, 2048 is the output dimension. Am I right?
And this output is the feature of a point, only feature, without the coordinate.

the coordinate is saved in the "batch", like the second parament in the line 332 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/architectures.py#L332

Does my understand right?
I try to add a self attention block between the block 12 and block 13, I try to let this block handle the output of the block12, and pass the result to the last block. It seems I don't need the parament "batch ".
Will this lead some mistake to the result? I hope I can get some advice from you!
 It's my honor to get your help!

**Comment by HuguesTHOMAS** [comment]
> Does the pytorch version different with the paper version? Does my understand correct?

Yes indeed, I must have experimented with different architectures at the time and kept this one. It usually does not make many differences in the performances, but you can indeed play with the architecture and eventually optimize it quite more than I did.

> I have some questions about the result. In my opinion, for example, the shape is [239,2048], 239 is the number of points in this batch, 2048 is the output dimension. Am I right?
And this output is the feature of a point, only feature, without the coordinate.

yes, you are right

> the coordinate is saved in the "batch", like the second parament in the line 332

yes, the point coordinate for layer `l` is stored in `batch.points[l]` to be exact, and has shape [N, 3], where N will be the same as the first dimension in your printed messages (239 for the last layer for example)

> I try to add a self attention block between the block 12 and block 13, I try to let this block handle the output of the block12, and pass the result to the last block. It seems I don't need the parament "batch ".
Will this lead some mistake to the result? 

Ok if you are trying to add a new block I think the most simple thing to do is to keep the same conventions I used. So keep the parameter `batch`, even if you do not need it. Here is what you should do:

1. Modify the config.architecture parameter to add your block in there:
    ```python
    architecture = [
                     ...

                    'resnetb',
                    'resnetb_strided',
                    'attention_block',
                    'resnetb',

                     ...

                    ]
    ```
    or something like that

2.  Go where I create the blocks

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/architectures.py#L234-L240

You can see that the `block_op `is returned by this function which takes some parameters:
`block`: the name of the block as a string, here: `'attention_block'`
`r`: current radius, only useful for convolutions, you will not need it
`in_dim`:  input dimension of the features (for you it should be 2048)
`out_dim`: output dimension of the features (for you it should still be 2048)
`layer`: the current layer index
`config`: all the config parameters

So you need to go and modify this block_decider function to add the ability to return your own block:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/blocks.py#L386-L426

There you can add an elif statement for your block, and pass any parameter you need as argument:

```python
     elif block_name == 'attention_block': 
         return AttentionBlock(in_dim, out_dim, any_other_parameter_you_need) 
```

**Comment by HuguesTHOMAS** [comment]
3. Then you can create the class for your block. Take inspiration from some of my own block classes in the _blocks.py_ file

For example the 

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/blocks.py#L469

define a simple MLP.

or even simpler the

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/3a774ff8d54a4d080fe65093b2299ede35d9735d/models/blocks.py#L651-L661

only return the average feature between all points.

Any parameter you need here can be passed through in the block decider function.

**Comment by HuguesTHOMAS** [comment]
4. Eventually you see that the forward function is always taking the feature tensor `x` and the `batch`, even if you do not need it.

Write you own forward function and you can just ignore the batch variable if you don't need it, like I do in the Unary block:

**Comment by BruceWayne233** [comment]
Hi Mr.Thomas
Wow! Thank you for your detailed and thoughtful answer. I've tried to implement the self-attention block and it leads to no bugs but there's no significant performance improvement. The improvement I've had is around 1%. I think it's probably because my data only has XYZ coordinate, and the way I implement the self-attention may mainly focus on the feature. If I add more features it may lead to an improvement. Do you have some advice for me?
Thank you for your considerate reply again! Wish you have a good day!
