### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'

### ISSUE THREAD

**Issue by Jaychouxq** [HuguesTHOMAS/KPConv-PyTorch#167]
ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'

It should be sklearn.neighbors._dist_metrics???

**Comment by thu-yao-01-luo** [comment]
I encounter the same problem as you. May I ask about the solution of the problem?

**Comment by thu-yao-01-luo** [comment]
> ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'
> 
> It should be sklearn.neighbors._dist_metrics???

I encounter the same problem as you. May I ask about the solution of the problem?
