### ISSUE TITLE
ScanNet training code?

### ISSUE THREAD

**Issue by lixingyi8947** [HuguesTHOMAS/KPConv-PyTorch#17]
Hi Hugues,

Could you provide a training script for ScanNet semantic segmentation task? Thanks a lot!

**Comment by HuguesTHOMAS** [comment]
Hi @lixingyi8947,

I am sorry this is not in my plan for now. You can write your own by copying the S3DIS training script and dataset class, and just adapting it for scannet scenes.

Best,
Hugues

**Comment by lixingyi8947** [comment]
Great, thanks!

**Comment by mutianxu** [comment]
Hi, @HuguesTHOMAS ,

Due to the data preprocessing may goes into many details in your work, transferring to ScanNet scenes from S3DIS training script is non-trivial. 

So could please give us some tips of adapting the S3DIS script to ScanNet?

Highly appreciated!
