### ISSUE TITLE
Thesis not available anymore

### ISSUE THREAD

**Issue by working12** [HuguesTHOMAS/KPConv-PyTorch#175]
Can you share your thesis link? You have mentioned it but none of the links works.

**Comment by HuguesTHOMAS** [comment]
Hi,

Here is a temporary link to the document, while I try to see what happened to the normal one.

[https://drive.google.com/file/d/1rpmdUp1bkj5RLuK4S9hO3DMXg6RkAt4e/view?usp=sharing](https://drive.google.com/file/d/1rpmdUp1bkj5RLuK4S9hO3DMXg6RkAt4e/view?usp=sharing)
