### ISSUE TITLE
killed when training on S3DIS

### ISSUE THREAD

**Issue by PPPPeterpan** [HuguesTHOMAS/KPConv-PyTorch#18]
@HuguesTHOMAS  thanks so much for your amazing work. However I got some problem when training on S3DIS dataset.
After Preparing KDTree  and Preparing ply files, the process is killed.
Could you please helps me to find what is happening here? Thanks so much in advance!

Starting Calibration (use verbose=True for more details)

Previous calibration found:
Check batch limit dictionary
"potentials_1.500_0.030_6": ?
Check neighbors limit dictionary
"0.030_0.075": ?
"0.060_0.150": ?
"0.120_0.720": ?
"0.240_1.440": ?
"0.480_2.880": ?
Step     1  estim_b = 0.10 batch_limit =    501
Step    27  estim_b = 0.94 batch_limit =  13501
Step    48  estim_b = 1.10 batch_limit =  23801
Step    68  estim_b = 1.72 batch_limit =  32501
Step    80  estim_b = 2.34 batch_limit =  36601
Step    91  estim_b = 2.44 batch_limit =  40501
Step   105  estim_b = 2.88 batch_limit =  44701
Step   115  estim_b = 3.13 batch_limit =  47401
Step   125  estim_b = 3.13 batch_limit =  50401
Step   136  estim_b = 3.59 batch_limit =  52801
Step   147  estim_b = 3.66 batch_limit =  55301
Step   157  estim_b = 3.85 batch_limit =  57301
Step   165  estim_b = 4.06 batch_limit =  58701
Step   169  estim_b = 3.86 batch_limit =  59701
Step   181  estim_b = 4.08 batch_limit =  61901
Step   190  estim_b = 4.40 batch_limit =  63201
Step   191  estim_b = 4.36 batch_limit =  63401
Step   200  estim_b = 4.52 batch_limit =  64601
Step   206  estim_b = 4.43 batch_limit =  65601
Step   215  estim_b = 4.53 batch_limit =  66901
Step   226  estim_b = 4.85 batch_limit =  68101
Step   232  estim_b = 4.60 batch_limit =  69101
Step   241  estim_b = 4.60 batch_limit =  70301
Step   249  estim_b = 4.47 batch_limit =  71601
Step   254  estim_b = 4.45 batch_limit =  72401
Step   256  estim_b = 4.55 batch_limit =  72601
Step   257  estim_b = 4.60 batch_limit =  72701
Step   259  estim_b = 4.86 batch_limit =  72701
Step   260  estim_b = 4.88 batch_limit =  72801
Step   261  estim_b = 4.79 batch_limit =  73001
Step   262  estim_b = 4.81 batch_limit =  73101
Step   264  estim_b = 4.85 batch_limit =  73301
Step   265  estim_b = 4.86 batch_limit =  73401
Step   266  estim_b = 5.08 batch_limit =  73301
Step   269  estim_b = 5.07 batch_limit =  73601
Killed

**Comment by HuguesTHOMAS** [comment]
Hi @PPPPeterpan,

Thanks for your interest. I really have no idea what happens here. I never encountered this error... 

Maybe you have run out of memory? Try reducing the input radius (`in_radius` variable) to 1.0 meter and see if it still bugs

**Comment by PPPPeterpan** [comment]
@HuguesTHOMAS 

Thanks so much for your quick reply.  I tried in pytorch 1.4 environment and it works now. 
and I run out of my 8g memory, just as you said.  So I change the grid size in subsampling to 5cm and then it works.
 
Thanks again for your reply. :)
