### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by E4CEeg** [HuguesTHOMAS/KPConv-PyTorch#186]
Hello, 
thank you for your great. While I was testing my own Dataset, I have encountered this error. 
My Dataset have files such as .bin , poses and calib. Please help me to solve this error 
Thank you

Data Preparation
****************
Preparing seq 00 class frames. (Long but one time only)
Preparing seq 01 class frames. (Long but one time only)
Traceback (most recent call last):
  File "/content/KPConv-PyTorch/train_SemanticKitti.py", line 265, in <module>
    balance_classes=False)
  File "/content/KPConv-PyTorch/datasets/SemanticKitti.py", line 149, in __init__
    self.load_calib_poses()
  File "/content/KPConv-PyTorch/datasets/SemanticKitti.py", line 575, in load_calib_poses
    seq_inds = np.hstack([np.ones(len(_), dtype=np.int32) * i for i, _ in enumerate(self.frames)])
  File "<__array_function__ internals>", line 6, in hstack
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by HuguesTHOMAS** [comment]
The error comes from here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/7d4c03d1996d31bf3330d6652ce3604afbe5345b/datasets/SemanticKitti.py#L575

It seems your `self.frames` list is not defined well. One of your sequences might not have any frames. Go back where `self.frames` is defined and ensure you have the list of all the names of the frames for all your sequences

**Comment by HuguesTHOMAS** [comment]
I pushed a correction, does it work now?

**Comment by E4CEeg** [comment]
Unfortunately no.

Traceback (most recent call last):
  File "/content/KPConv-PyTorch/train_SemanticKitti.py", line 286, in <module>
    training_sampler.calib_max_in(config, training_loader, verbose=True)
  File "/content/KPConv-PyTorch/datasets/SemanticKitti.py", line 924, in calib_max_in
    for batch_i, batch in enumerate(dataloader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1086, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1119, in _reset
    self._try_put_index()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1353, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 642, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 247, in __iter__
    for idx in self.sampler:
  File "/content/KPConv-PyTorch/datasets/SemanticKitti.py", line 812, in __iter__
    self.dataset.epoch_inds += gen_indices
RuntimeError: The size of tensor a (4400) must match the size of tensor b (464) at non-singleton dimension 0

**Comment by E4CEeg** [comment]
i have changed the highlighted int32 into int64

if self.dataset.balance_classes:

            # Initiate current epoch ind
            self.dataset.epoch_i *= 0
            self.dataset.epoch_inds *= 0
            self.dataset.epoch_labels *= 0

            # Number of sphere centers taken per class in each cloud
            num_centers = self.dataset.epoch_inds.shape[0]

            # Generate a list of indices balancing classes and respecting potentials
            gen_indices = []
            gen_classes = []
            for i, c in enumerate(self.dataset.label_values):
                if c not in self.dataset.ignored_labels:

                    # Get the potentials of the frames containing this class
                    class_potentials = self.dataset.potentials[self.dataset.class_frames[i]]

                    if class_potentials.shape[0] > 0:

                        # Get the indices to generate thanks to potentials
                        used_classes = self.dataset.num_classes - len(self.dataset.ignored_labels)
                        class_n = num_centers // used_classes + 1
                        if class_n < class_potentials.shape[0]:
                            _, class_indices = torch.topk(class_potentials, class_n, largest=False)
                        else:
                            class_indices = torch.zeros((0,), **dtype=torch.int64**)
                            while class_indices.shape[0] < class_n:
                                new_class_inds = torch.randperm(class_potentials.shape[0]).type(**torch.int64**)
                                class_indices = torch.cat((class_indices, new_class_inds), dim=0)
                            class_indices = class_indices[:class_n]
                        class_indices = self.dataset.class_frames[i][class_indices]

                        # Add the indices to the generated ones
                        gen_indices.append(class_indices)
                        gen_classes.append(class_indices * 0 + c)

                        # Update potentials
                        update_inds = torch.unique(class_indices)
                        self.dataset.potentials[update_inds] = torch.ceil(self.dataset.potentials[update_inds])
                        self.dataset.potentials[update_inds] += torch.from_numpy(np.random.rand(update_inds.shape[0]) * 0.1 + 0.1)

            # Stack the chosen indices of all classes
            gen_indices = torch.cat(gen_indices, dim=0)
            gen_classes = torch.cat(gen_classes, dim=0)

            # Shuffle generated indices
            rand_order = torch.randperm(gen_indices.shape[0])[:num_centers]
            gen_indices = gen_indices[rand_order]
            gen_classes = gen_classes[rand_order]

            # Update potentials (Change the order for the next epoch)
            #self.dataset.potentials[gen_indices] = torch.ceil(self.dataset.potentials[gen_indices])
            #self.dataset.potentials[gen_indices] += torch.from_numpy(np.random.rand(gen_indices.shape[0]) * 0.1 + 0.1)

            # Update epoch inds
            self.dataset.epoch_inds += gen_indices
            self.dataset.epoch_labels += gen_classes.type(**torch.int64**)

        else:

            # Initiate current epoch ind
            self.dataset.epoch_i *= 0
            self.dataset.epoch_inds *= 0
            self.dataset.epoch_labels *= 0

            # Number of sphere centers taken per class in each cloud
            num_centers = self.dataset.epoch_inds.shape[0]

            # Get the list of indices to generate thanks to potentials
            if num_centers < self.dataset.potentials.shape[0]:
                _, gen_indices = torch.topk(self.dataset.potentials, num_centers, largest=False, sorted=True)
            else:
                gen_indices = torch.randperm(self.dataset.potentials.shape[0])
                while gen_indices.shape[0] < num_centers:
                    new_gen_indices = torch.randperm(self.dataset.potentials.shape[0]).type(**torch.int64**)
                    gen_indices = torch.cat((gen_indices, new_gen_indices), dim=0)
                gen_indices = gen_indices[:num_centers]

            # Update potentials (Change the order for the next epoch)
            self.dataset.potentials[gen_indices] = torch.ceil(self.dataset.potentials[gen_indices])
            self.dataset.potentials[gen_indices] += torch.from_numpy(np.random.rand(gen_indices.shape[0]) * 0.1 + 0.1)

            # Update epoch inds
            self.dataset.epoch_inds += gen_indices

**Comment by HuguesTHOMAS** [comment]
This mistake should not be happening with the recent corrections I made on the repo.
How many frames does each of your sequences contain?

**Comment by E4CEeg** [comment]
I believe training set has 400 , validation has 39 and test has 144 frames

**Comment by HuguesTHOMAS** [comment]
I see this is really small. You should definitely reduce the number of steps per epoch

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/e5be3ce280f580b9017d2dc194f4475732843eb1/train_SemanticKitti.py#L163

Something like 50 should be more appropriate in your case. Same for validation size:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/e5be3ce280f580b9017d2dc194f4475732843eb1/train_SemanticKitti.py#L166

Use something like 10 or 5

**Comment by E4CEeg** [comment]
i still have the same error.

Previous calibration found:
Check max_in limit dictionary
"balanced_4.000_0.060": ?
Traceback (most recent call last):
  File "/content/KPConv-PyTorch/train_SemanticKitti.py", line 286, in <module>
    training_sampler.calib_max_in(config, training_loader, verbose=True)
  File "/content/KPConv-PyTorch/datasets/SemanticKitti.py", line 922, in calib_max_in
    for batch_i, batch in enumerate(dataloader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1086, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1119, in _reset
    self._try_put_index()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1353, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 642, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 247, in __iter__
    for idx in self.sampler:
  File "/content/KPConv-PyTorch/datasets/SemanticKitti.py", line 810, in __iter__
    self.dataset.epoch_inds += gen_indices
RuntimeError: The size of tensor a (441) must match the size of tensor b (48) at non-singleton dimension 0

**Comment by HuguesTHOMAS** [comment]
Ok, I think there is a problem with your dataset statistics. I pushed a correction to see what happens. Can you print the error message now?

**Comment by E4CEeg** [comment]
ValueError: 
This error is raised if one of the classes is not ignored and does not appear in any of the frames of the dataset.

**Comment by HuguesTHOMAS** [comment]
There you go. Your dataset is not well defined. You are training your network to predict a certain number of classes but some of them are not even present in your data. I pushed a new version of the error message where it shows the stats.

**Comment by HuguesTHOMAS** [comment]
Yes, that is the best option.

Or if you want to keep it like this, you can use balance_class=False when creating your dataset. But it does not make sense to use classes that are not present in your dataset

**Comment by E4CEeg** [comment]
Thank you very much for your help
