### ISSUE TITLE
when training sematickitti, it appears a ValueError: Truth values are stored in a 0D array instead of 1D array 

### ISSUE THREAD

**Issue by alualu628628** [HuguesTHOMAS/KPConv-PyTorch#20]
I rename the project as HPC-Resnet.
I train sematickitti, it works well at the beginning. 
Howerver, it appears a valueError: Truth values are stored in a 0D array instead of 1D array when the epoch reaches at 160 or more (sometimes at about 460 or 680).
I dont know what happens. I think this may be something in data processing.

File "train_SemanticKitti.py", line 324, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "/home/ludy/PythonWorkSpace/HPC-Resnet/utils/trainer.py", line 271, in train
    self.validation(net, val_loader, config)
  File "/home/ludy/PythonWorkSpace/HPC-Resnet/utils/trainer.py", line 289, in validation
    self.slam_segmentation_validation(net, val_loader, config)
  File "/home/ludy/PythonWorkSpace/HPC-Resnet/utils/trainer.py", line 801, in slam_segmentation_validation
    Confs[i, :, :] = fast_confusion(truth, preds, val_loader.dataset.label_values).astype(np.int32)
  File "/home/ludy/PythonWorkSpace/HPC-Resnet/utils/metrics.py", line 48, in fast_confusion
    raise ValueError('Truth values are stored in a {:d}D array instead of 1D array'. format(len(true.shape)))
ValueError: Truth values are stored in a 0D array instead of 1D array

**Comment by HuguesTHOMAS** [comment]
This is strange it seems to mean you are using scenes without labels during validation. Are you sure you downloaded and processed the dataset correctly? And use the sequence 8 for validation? I never had this error.

**Comment by EthanZhangYi** [comment]
@HuguesTHOMAS 
I also met the same problem, not at the first epoch, but at the 389th epoch.
![image](https://user-images.githubusercontent.com/13479831/87748228-e76a3b00-c827-11ea-99a1-0cc29afb0d73.png)

**Comment by HuguesTHOMAS** [comment]
From what I remember of the code, I use projection indices and projection mask. This truth array is computed with it:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/utils/trainer.py#L777

This projection mask is part of the batch data:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/utils/trainer.py#L715-L716

There is obviously a problem with this array. You can try to print its shape and look into the way it is created there:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/9bae9a3a2a04a3675fa4ec6e5993711438a32e9f/datasets/SemanticKitti.py#L370-L380

You could end up with an empty mask if p0 is wrong. Let me know if this is the reason or if it was something else.

**Comment by alualu628628** [comment]
The variable “true” seems to have a point, which at fast_confusion(true, pred, label_values=None) in utils/metrics.py 
In this case, the variable “true” would be compressed.
I thus add a condition and do not meet this issue any more:
```
    if true.shape[0] != 1:
        true = np.squeeze(true)
    if pred.shape[0] != 1:
        pred = np.squeeze(pred)
```

**Comment by Xigui-Li** [comment]
> @HuguesTHOMAS 我也遇到了同样的问题，不是在第一个纪元，而是在第 389 个纪元。 ![图像](https://user-images.githubusercontent.com/13479831/87748228-e76a3b00-c827-11ea-99a1-0cc29afb0d73.png)

Hello, I encountered the same error as you did. May I ask how you resolved it?
