### ISSUE TITLE
multi-gpu implementation

### ISSUE THREAD

**Issue by ginobilinie** [HuguesTHOMAS/KPConv-PyTorch#21]
Thanks for your great work. I'm wondering if it is easy to implement it in a multi-gpu manner based on this repository?

**Comment by HuguesTHOMAS** [comment]
Hi @ginobilinie,

I never tried it myself but I know some people have done it so it should be possible yes. I am sorry I can't help you with this, you should look a PyTorch multi-gpu guides and adapt this repo.

Best,
Hugues

**Comment by ginobilinie** [comment]
Thanks.
