### ISSUE TITLE
How is mIoU calculated on the Paris-Lille-3D dataset in your paper KPConv

### ISSUE THREAD

**Issue by xiaohe3625** [HuguesTHOMAS/KPConv-PyTorch#213]
Hi Dr.HuguesTHOMAS, Thank you for your great work！I have a question for you. How is mIoU calculated on the Paris-Lille-3D dataset in your paper KPConv? Is it Val_IoUs.txt averaging each category of IoU by  this text?

**Comment by HuguesTHOMAS** [comment]
The validation scores are computed on the whole validation clouds in our testing function:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/1defcd75cf7c0399704a6a9f63d3a550bfb8c1c9/utils/tester.py#L176

In particular here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/1defcd75cf7c0399704a6a9f63d3a550bfb8c1c9/utils/tester.py#L354

The test score are values returned by an online benchmark when we submitted the test predictions:
https://npm3d.fr/paris-lille-3d

**Comment by xiaohe3625** [comment]
Thank you, I see that these codes save the prediction results.
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/1defcd75cf7c0399704a6a9f63d3a550bfb8c1c9/utils/tester.py#L452-L453
What should I do when I want to evaluate a point cloud scene with labels? mIoU and Acc are calculated by real labels and predicted labels, do you provide the code?

**Comment by xiaohe3625** [comment]
Thanks for your help.
