### ISSUE TITLE
Caught IndexError in DataLoader worker process 0

### ISSUE THREAD

**Issue by WesamOM** [HuguesTHOMAS/KPConv-PyTorch#221]
When running tarin_S3DIS.py I keep running into this error and I am not sure why it's happening. The program works until it hits e000-i0500 and gives me an error that val_loader is 0.

Error is as following:
e000-i0480 => L=3.674 acc= 70% / t(ms):  41.1 236.9 277.6)
e000-i0482 => L=4.151 acc= 61% / t(ms):  40.9 237.8 278.1)
e000-i0484 => L=3.557 acc= 73% / t(ms):  40.5 233.8 275.5)
e000-i0486 => L=3.822 acc= 65% / t(ms):  40.7 232.2 276.1)
e000-i0488 => L=4.131 acc= 64% / t(ms):  39.7 226.9 273.3)
e000-i0490 => L=4.003 acc= 69% / t(ms):  39.8 224.8 270.7)
e000-i0492 => L=4.339 acc= 66% / t(ms):  39.2 225.5 266.3)
e000-i0494 => L=3.391 acc= 78% / t(ms):  39.7 226.7 267.9)
e000-i0496 => L=4.267 acc= 57% / t(ms):  40.6 222.2 266.8)
e000-i0498 => L=4.300 acc= 54% / t(ms):  40.8 221.8 265.4)
Traceback (most recent call last):
  File "C:\Users\WOmran\KPConv-PyTorch-master\train_S3DIS.py", line 329, in <module>
    trainer.train(net, training_loader, test_loader, config)
  File "C:\Users\WOmran\KPConv-PyTorch-master\utils\trainer.py", line 274, in train
    self.validation(net, val_loader, config)
  File "C:\Users\WOmran\KPConv-PyTorch-master\utils\trainer.py", line 290, in validation
    self.cloud_segmentation_validation(net, val_loader, config)
  File "C:\Users\WOmran\KPConv-PyTorch-master\utils\trainer.py", line 471, in cloud_segmentation_validation
    for i, batch in enumerate(val_loader):
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WOmran\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\WOmran\KPConv-PyTorch-master\datasets\S3DIS.py", line 239, in __getitem__
    return self.potential_item(batch_i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WOmran\KPConv-PyTorch-master\datasets\S3DIS.py", line 300, in potential_item
    cloud_ind = int(torch.argmin(self.min_potentials))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: argmin(): Expected reduction dim to be specified for input.numel() == 0.

Can someone help?

**Comment by Yarroudh** [comment]
What was the solution as you closed the issue?

**Comment by WesamOM** [comment]
Oh I believe I was having this issue because I wanted to do a quick test of KPConv with S3DIS data. So I had changed 
`self.cloud_names = ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_5', 'Area_6']` in line 114 in S3DIS.py to 
`self.cloud_names = ['Area_1']`
Which was causing the program to crash. If I needed to test it only on Area_1, I would've had to change so many other parameters in the code. I ended up let it train for a week, mind you I am using a GTX 1080 graphics card.

**Comment by Yarroudh** [comment]
Thanks for your reply, I was trying to train on my dataset, I found out that my .las files were not in the right directory for pre-processing, I just moved them there and it works. Sometimes I feel stupid for these kind of errors :)

**Comment by WesamOM** [comment]
No worries, I've been having a lot of trouble myself with KPConv. A quick question though, how did you make KPConv train .las files, the S3DIS data doesn't have .las files. I am trying to figure out how to do that. From what I understand is that S3DIS data is formatted in text files, where each room has objects with a corresponding text file that contains: x, y, z, r, g, b. Then KPConv converts them into .ply files that train_S3DIS.py then understands and processes.

**Comment by Yarroudh** [comment]
It's not training on .las files but on .ply files, what I did is that I read the data using `laspy`, then I write .ply files using data retrieved from the .las files. Here is how I do it in `train_S3DIS.py`:

```python
def prepare_S3DIS_ply(self):

        print('\nPreparing ply files')
        t0 = time.time()

        # Folder for the ply files
        ply_path = join(self.path, self.train_path)
        if not exists(ply_path):
            os.mkdir(ply_path)

        for cloud_name in self.cloud_names:

            # Pass if the cloud has already been computed
            cloud_file = join(ply_path, cloud_name + '.ply')
            if exists(cloud_file):
                print('{:s} already done'.format(cloud_name))
                continue

            # Get (X, Y, Z) points
            print('\nPreparing ply for cloud {:s}\n'.format(cloud_name))
            lasfile = laspy.read(join(self.path, cloud_name + '.las'))
            cloud_points = np.vstack((lasfile.x, lasfile.y, lasfile.z)).transpose()
            cloud_colors = np.vstack((lasfile.red, lasfile.green, lasfile.blue)).transpose()
            cloud_colors = cloud_colors.astype(np.uint8)
            cloud_classes = lasfile.classification

            # Save as ply
            write_ply(cloud_file,
                      (cloud_points, cloud_colors, cloud_classes),
                      ['x', 'y', 'z', 'red', 'green', 'blue', 'class'])

        print('Done in {:.1f}s'.format(time.time() - t0))
        return
```

I'm actually trying to train KPConv on TUMFACADE data which comes as .las files. I also do not have RGB values so I replaced them in my code with some geometric features.

**Comment by WesamOM** [comment]
I appreciate your quick response. This explained a lot to me. 
I am trying to use KPConv for training custom LiDAR data.

**Comment by WesamOM** [comment]
@Yarroudh 
I took your code and tried to run it on DALES dataset:
`    def prepare_DALES_ply(self):

        print('\nPreparing ply files')
        t0 = time.time()

        # Folder for the ply files
        ply_path = join(self.path, self.train_path)
        if not exists(ply_path):
            os.mkdir(ply_path)

        for cloud_name in self.cloud_names:

            # Pass if the cloud has already been computed
            cloud_file = join(ply_path, cloud_name + '.ply')
            if exists(cloud_file):
                print('{:s} already done'.format(cloud_name))
                continue

            # Get (X, Y, Z) points
            print('\nPreparing ply for cloud {:s}\n'.format(cloud_name))
            lasfile = laspy.read(join(self.path, cloud_name + '.las'))
            cloud_points = np.vstack((lasfile.x, lasfile.y, lasfile.z)).transpose()
            r = []
            g = []
            b = []
            for i in range(len(lasfile.x)):
                r.append(0)
                g.append(0)
                b.append(0)
            cloud_colors = np.vstack((r, g, b)).transpose()
            cloud_colors = cloud_colors.astype(np.uint8)
            cloud_classes = lasfile.classification
            field_names = ['x', 'y', 'z', 'red', 'green', 'blue', 'class']

            # Save as ply
            write_ply(cloud_file,
                      [cloud_points, cloud_colors, cloud_classes],
                      field_names)

        print('Done in {:.1f}s'.format(time.time() - t0))
        return`
The following part of the code is just to fill arbitrary meaningless values for rgb, since DALES .las files don't have rgb values:
`r = []
            g = []
            b = []
            for i in range(len(lasfile.x)):
                r.append(0)
                g.append(0)
                b.append(0)`

Now whenever I run it, I keep getting this error, not sure why:
  File "C:\Users\WOmran\KPConv-PyTorch-master\train_DALES.py", line 272, in <module>
    training_dataset = DALESDataset(config, set='training', use_potentials=True)
  File "C:\Users\WOmran\KPConv-PyTorch-master\datasets\DALES.py", line 137, in __init__
    self.prepare_DALES_ply()
  File "C:\Users\WOmran\KPConv-PyTorch-master\datasets\DALES.py", line 679, in prepare_DALES_ply
    write_ply(cloud_file,
  File "C:\Users\WOmran\KPConv-PyTorch-master\utils\ply.py", line 254, in write_ply
    field_list[i] = field.shape(-1, 1)
TypeError: 'tuple' object is not callable

Not sure if you ran into this error or not, but would appreciate it if you could help :)

**Comment by Yarroudh** [comment]
I think `field.shape(-1, 1)` should be `field.reshape(-1, 1)`. The `shape` attribute of a numpy array returns a tuple representing the dimensions of the array, and it is not callable. Try to modify **line 254** in **utils/ply.py**.

I checked my file and I found this code: `field_list[i] = np.array(field).reshape(-1, 1)`

Note: using random RGB value will give bad results. I advise you to calculate some geometric features like planarity, verticality, linearity, surface variation, roughness, etc. and then use them for training instead of RGB values. These geometric features can be calculated in cloud compare and save it as extra dimensions when exporting. You can also use other fields like intensity, or number of returns, etc.

```python
cloud_points = np.vstack((lasfile.x, lasfile.y, lasfile.z)).transpose()
cloud_features = np.vstack((las.Planarity, las.Linearity, las.Roughness)).transpose()
cloud_classes = lasfile.classification
field_names = ['x', 'y', 'z', 'Planarity', 'Linearity', 'Roughness', 'class']
```

I never tried more than three features, so I don't know exactly if it's going to work with more than that, you can give it a try.

**Comment by WesamOM** [comment]
I appreciate your help and advice. I'll be experimenting with it for sure in the future. 
Also thanks for helping me resolve the issue, it was just that I needed to change `field.shape(-1, 1)` to `field.reshape(-1, 1)` and adding the `np.array(field)`. Not sure what happened exactly when I copied your code at the beginning. Nonetheless, I really appreciate it.
