### ISSUE TITLE
using Kpconv semantic segmentation for the room segmentation

### ISSUE THREAD

**Issue by shayan-nikoo** [HuguesTHOMAS/KPConv-PyTorch#222]
Hi Thomas,

Thanks for your nice work.
In S3DIS we have over 300 rooms. Do you think we can use Kpconv sem. segmentation on S3DIS to train the model to do a room segmentation task? By room segmentation I mean the output of the model is the room number of the Area. This is a little bit difficult to formulate as a classification or semantic segmentation task rather more similar to a planar segmentation task where each point gets the id of the plane it belongs to. Obviously, the number of rooms is not a fixed number like the fixed classes that we have in sem. segmentation, since Areas have different number of rooms. So what are your thoughts about this? Is it possible to train the model to learn the physical spaces? 

![image](https://github.com/HuguesTHOMAS/KPConv-PyTorch/assets/123162959/f671c906-7eec-488d-9c2b-5e7e75f96ff8)

Image from: https://ieeexplore.ieee.org/document/8019484

**Comment by shayan-nikoo** [comment]
Thanks. Also, a 2D sectioning along the z-axis and segmentation can work but I was looking more for a 3D approach with no intermediate data processing. I'll try Mask3D, thanks for the suggestion.

Get back to your first point, I can imagine for room classification (office, copy room, bedroom,...) we can heavily subsample room instances and then run a classification training where each room is an object, right? In this case, isn't a room instance too large for the model compared to other classification datasets where an object is an airplane or a chair?

Could you elaborate on that?

**Comment by HuguesTHOMAS** [comment]
It would only be as big as you want it to be, depending on the subsampling size. The actual size does not matter for memory consumption, only the number of points
