### ISSUE TITLE
Segmentation fault (core dumped) when executing "train_ModelNet40.py"

### ISSUE THREAD

**Issue by amiltonwong** [HuguesTHOMAS/KPConv-PyTorch#23]
Hi, @HuguesTHOMAS ,

When I execute `python train_ModelNet40.py`, I got the Segmentation fault error as the following:

```
Data Preparation
****************

Loading training points subsampled at 0.020
1620.2 MB loaded in 367.4s

Loading test points subsampled at 0.020

411.6 MB loaded in 40.1s

Starting Calibration (use verbose=True for more details)
Segmentation fault (core dumped)
(pytorch1.4) root@milton-ThinkCentre-M93p:/data/code10/KPConv-PyTorch# 

```

Any hints to solve this issue?

THX!

**Comment by HuguesTHOMAS** [comment]
Hi @amiltonwong,

Mmmh, I would guess it has something to do with the cpp wrappers, maybe the was a problem when you compiled them? I you set the `num_workers` to 0, then you'll be able to track down where the segmentation fault happens in the python code, and see if it is one of the cpp wrappers.
