### ISSUE TITLE
AttributeError: module 'cpp_wrappers.cpp_neighbors.neighbors' has no attribute 'batch_query'

### ISSUE THREAD

**Issue by LinLin1031** [HuguesTHOMAS/KPConv-PyTorch#230]
![image](https://github.com/HuguesTHOMAS/KPConv-PyTorch/assets/50825626/dc9c5269-cfc1-4081-a002-366dc10c80ce)

May I ask how this problem can be solved? I have tried several times to delete the "cpp_wrappers" folder and recompile it, but it doesn't work.

**Comment by LinLin1031** [comment]
@HuguesTHOMAS Hello! I hope you'll help me at your convenience.

**Comment by LinLin1031** [comment]
It's been solved, it was a naming issue when importing "radius_neighbors" packages in "common.py".

**Comment by moniec1717** [comment]
Hi, 

could you pls explain the solution in more detail? I‘ve run into the same problem. Does this mean I need to change the name of the 'radius_neighbors' when I import it into 'common.py'?

best regards,

**Comment by yuyuyuyy11** [comment]
> It's been solved, it was a naming issue when importing "radius_neighbors" packages in "common.py".

Hello, can you explain in detail how to solve this problem? Thank you

**Comment by LinLin1031** [comment]
> > It's been solved, it was a naming issue when importing "radius_neighbors" packages in "common.py".它已经解决了，在 “common.py” 中导入 “radius_neighbors” 包时出现命名问题。
> 
> Hello, can you explain in detail how to solve this problem? Thank you您好，您能详细解释一下如何解决这个问题吗？谢谢


https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/22a178831a6559716cf1213bf99df22dc45efc53/datasets/common.py#L36

That's the line, you could try changing it to `import cpp_wrappers.radius_neighbors as cpp_neighbors`.
