### ISSUE TITLE
Train a custom point cloud dataset with 50 more features

### ISSUE THREAD

**Issue by aldinorizaldy** [HuguesTHOMAS/KPConv-PyTorch#236]
Hi Thomas,
thanks for the great works. I hope you are still around to answer my questions.

I am working on a point cloud data with hyperspectral features, so you can think about point with XYZ + RGB + 50 features. I know how you prepared S3DIS dataset by having 5 features (1 + RGB + height) for the `in_features_dim`. But how if I have more features? I would think of 1 + RGB + 1 height + 50 = 55. Is that correct?

If so, where should I change the code? I see there are several things to do:

1. Change the `in_features_dim` to 55
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/8ec7478cd6b5fa3c6f423b984d6817b5e90e057b/train_S3DIS.py#L146
2. Add something similar to this but `elif self.config.in_features_dim == 55:`
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/8ec7478cd6b5fa3c6f423b984d6817b5e90e057b/datasets/S3DIS.py#L418-L419
3. Then this is something that I don't understand. How does the `input_colors` collect the RGB features? If I have RGB + 50 more features, then how should I change this code?
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/8ec7478cd6b5fa3c6f423b984d6817b5e90e057b/datasets/S3DIS.py#L353-L372

Thanks!!

**Comment by HuguesTHOMAS** [comment]
Hi @aldinorizaldy,

Because S3DIS dataset is small enough to be loaded entirely in memory, we preload the point clouds and their colors in this function:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/8ec7478cd6b5fa3c6f423b984d6817b5e90e057b/datasets/S3DIS.py#L715C17-L715C17

More precisely here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/8ec7478cd6b5fa3c6f423b984d6817b5e90e057b/datasets/S3DIS.py#L757-L790

If you can do the same then great. If not you might have to load from file directly in the get_item function. Actually if your dataset consists of several small file (lets say various different rooms) It might be better to load it directly in the get_item function to avoid using to much memory by preloading everything

**Comment by aldinorizaldy** [comment]
Hi Thomas,

Perfect!! Thank you for answering my question. I had an error with the `expected_N` value, but I solved it by reducing the value into 1e4. Now I'm able to train my custom data. 

It is an outdoor lidar with sparse point density. So I have to play around with the `in_radius `and `first_subsampling_dl`. The average point spacing is 2 m, so I chose `first_subsampling_dl` = 2 and `in_radius` = 100, following your advice to have a consant ratio more or less 50x. Having less values for both parameters gave me worse results.

Thank you again for still being here and help the community.
I do really appreciate it.
Cheers!!

**Comment by HuguesTHOMAS** [comment]
Thanks for your kind message!

Best,
Hugues

**Comment by xxy-nolooker** [comment]
Dear experts,

I have encountered a similar issue. My data is evenly sampled with a point spacing of 2 m, and I have set first_subsampling_dl = 1 and in_radius = 85. Could you please advise whether these parameter settings are reasonable? Additionally, I would appreciate any guidance you can provide on adjusting KP_extent.

Thank you very much for your assistance.

Best regards
Xiangyu Xu

**Comment by xxy-nolooker** [comment]
Hi @aldinorizaldy,

Thank you so much for your insightful comment. I also noticed that setting first_subsampling_dl = 1 leads to almost no actual downsampling in the first layer, which aligns with what you pointed out. At the same time, I observed that when in_radius = 100, many points end up having the exact same neighbors, which feels a bit off — perhaps I’ve misunderstood something in the process.

In any case, I really appreciate your help and suggestions. It definitely helped me clarify a few things.

Best regards,
xxy-nolooker

**Comment by aldinorizaldy** [comment]
Hi @xxy-nolooker, you could check the explanation by the author here:
- https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/180#issuecomment-1170493163
- https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/156#issuecomment-1076355335
- https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/191#issuecomment-1203838288

The in_radius defines the size of the spheres. If you are working with large outdoor data, and want to classify large objects, then having a large in_radius is necessary. Since you were saying your data has 2 m point spacing, I would assume you are working with outdoor scene. The correct number for in_radius totally depends on your dataset. 

Regarding having the exact same neighbors, I'm not really sure what you mean. But please remember that the preprocessing generates (regular) spheres with some overlaps. Let's say you have point cloud in area of 500 x 500 m, then you need to draw subcloud (in sphere) regularly, with 50 m radius (or whatever). These spheres will have some overlaps each other. 

At least that is my understanding of the preprocessing.

**Comment by xxy-nolooker** [comment]
Hi @aldinorizaldy , thank you so much for your detailed and patient explanation! 🙏

My dataset comes from a rather unusual domain—cryo-electron microscopy (cryo-EM)—which is quite different from typical outdoor LiDAR scans. I believe I've finally pinpointed the root of my issue:

My dataset isn't very standardized—point counts vary a lot between samples.

The neighborhood computation does include the query point itself.

I mistakenly chose a relatively large in_radius, which, combined with the above, resulted in many different points having nearly identical neighborhoods.

Your insights really helped me connect the dots. As a beginner in this area, I’ve learned a lot from your reply. Thanks again! 🚀
Best regards,
xxy-nolooker
