### ISSUE TITLE
Why is in_features_dim = 5 for S3DIS?

### ISSUE THREAD

**Issue by DarylWM** [HuguesTHOMAS/KPConv-PyTorch#245]
Thank you for sharing this project; I'm finding the code to be clear and well commented, which makes it easier to understand.

One parameter I don't undestand though is why [the input features dimension is 5](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/435d117c1bb2f82d7030a669444b8f20976b7a6a/train_S3DIS.py#L146) for the S3DIS dataset. Why would it not be 6, for (x,y,z,r,g,b)?

Daryl.

**Comment by LucaRom** [comment]
Hi, the features_dimension value does not include the x, y, z coordinates, it's for the number of extra features to include in the training. For example S3DIS as R,G,B,D (depth layer). KPConv adds a feature of 1's to all training by default.

Related answer by the author :
[https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/156#issuecomment-1081892752](https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/156#issuecomment-1081892752)

**Comment by DarylWM** [comment]
Thank you very much. I had missed that previous answer.
