### ISSUE TITLE
batch_num of pytorch version is smaller than that of tf version

### ISSUE THREAD

**Issue by ginobilinie** [HuguesTHOMAS/KPConv-PyTorch#25]
Hi Hugues,

I have tried both the tf version and pytorch version of KPConv, I'd like to ask why the batch_num of pytorch version is smaller than tf version? According to my experience, I found pytorch version cost more memory than tf version. 

Thanks.

**Comment by HuguesTHOMAS** [comment]
Hi @ginobilinie,

Pytorch version should not cost more memory than tf version. I think the reason you experienced more memory cost with PytTorch is becauseI use deeper networks. If you try with the same architecture I don't think you would see much of a difference.

Besy,
Hugues

**Comment by ginobilinie** [comment]
@HuguesTHOMAS Thanks for your reply.

I have checked the architecture, both of them are:

    # Define layers
    architecture = ['simple',
                    'resnetb',
                    'resnetb_strided',
                    'resnetb',
                    'resnetb_strided',
                    'resnetb_deformable',
                    'resnetb_deformable_strided',
                    'resnetb_deformable',
                    'resnetb_deformable_strided',
                    'resnetb_deformable',
                    'nearest_upsample',
                    'unary',
                    'nearest_upsample',
                    'unary',
                    'nearest_upsample',
                    'unary',
                    'nearest_upsample',
                    'unary']

So is there any other factor may affect the cost memory of the network?

**Comment by HuguesTHOMAS** [comment]
If I remember correctly, there are some differences in the way I implemented deformable convolution, so that could be a reason. If you still see a big difference when using the standard KPConv, then there might be some implementation issues in the PyTorch version.

I know from another issue, that it is advisable to wrap the validation loop in a torch.no_grad loop, to save memory. I did not correct it at this point, so that could also be a reason.

**Comment by ginobilinie** [comment]
Thanks. I'll try the torch.no_grad today.

I set the deform_radius = 6.0 in pytorch version, while I cannot see the related hyperparameter in https://github.com/HuguesTHOMAS/KPConv/blob/master/training_NPM3D.py

Do you think it is one of the reason?

**Comment by HuguesTHOMAS** [comment]
This is something that changed a little bit in the new implementation.

Before, we used `density _parameter` as the deformable radius, for rigid KPConv, the convolution radius was automatically set to `2.5 * KP_extent` . To give more freedom to the rigid KPConv, I know have a specific `conv_radius `parameter, so the KP_extend can be modified without changing the convolution radius

To answer your question, it could be a reason, as if I recall, the  `density _parameter`  was set to 5 and not 6 before.

**Comment by ginobilinie** [comment]
I see. Thanks. I'll try and let you know the result.
