### ISSUE TITLE
Data Preprocessing for SemanticKitti

### ISSUE THREAD

**Issue by lixingyi8947** [HuguesTHOMAS/KPConv-PyTorch#26]
Hi,

May I ask that could you provide some references for the data prereprocessing for SemanticKitti dataset? It seems there are several different steps. I am new to SLAM segmentation. Thanks!

**Comment by HuguesTHOMAS** [comment]
Hi @lixingyi8947,

I am affraid I have no reference for you. I just implemented what I believed was smart. I generally comment a lot my code, which should make it easier for you too follow.
Best,
Hugues
