### ISSUE TITLE
multi-processing on Windows

### ISSUE THREAD

**Issue by yaping222** [HuguesTHOMAS/KPConv-PyTorch#27]
Hi Hugues,

I'm running the Pytorch codes on Windows system. When I set 'num_workers' in Dataloader to a value larger than 0, the training is slower than when 'num_workers' is set as 0.
However, when I run the code on Linux, the training is faster with a larger 'num_workers'.
I wonder whether you met the same issue on Windows system.

Best wishes,
Yaping

**Comment by HuguesTHOMAS** [comment]
Hi @yaping222,

this is strange but not surprising. I remember seeing somewhere in the documentation of PyTorch that multi-processing behaviors on windows and Linux are not the same. In my case I only tried the compilation on a windows machine but I did not experienced real trainings. 

If you are able to find a solution to this problem, I would be glad to know it.

Best,
Hugues

**Comment by yaping222** [comment]
Hi @HuguesTHOMAS ,

Thank you very much. I will let you know if I find a solution.

Best wishes,
Yaping
