### ISSUE TITLE
vote accuracy

### ISSUE THREAD

**Issue by tangbohu** [HuguesTHOMAS/KPConv-PyTorch#30]
I could see vote accuray and validation accuray in the plot reuslts. What does "vote acc" means? 
Besides, why there are votes in the test function, should we run (i.e.) 100 times to get an averaged results? Thanks and looking forward to your kind reply!

**Comment by shangguan91** [comment]
same of problem of results interpretation, i do not understand the result.
![image](https://user-images.githubusercontent.com/64595972/89915591-d4644400-dbf6-11ea-86d8-6dacf3f500de.png)


 it would be nice if train_acc, test_acc for each epoch could be printed.

**Comment by tangbohu** [comment]
Move to the another issue.
