### ISSUE TITLE
model numbers per epoch setting when my own data ist implemented

### ISSUE THREAD

**Issue by shangguan9191** [HuguesTHOMAS/KPConv-PyTorch#31]
The setting on modelnet40 is following ,if self.train: self.num_models = 9843.
does num_models mean samples? 

i have 60 samples of my own data with obj file format. So, i should set this number to 40? 
and what is identical code for loadtxt, is there load.obj?  if not, is there anyway to convert obj to txt.

**Comment by HuguesTHOMAS** [comment]
Yeah, num_models is the number of models. Let's say you have 60 models and you use 5 of them for validation, then, you would do:

    if self.train:
        self.num_models = 55
    else:
        self.num_models = 5

**Comment by shangguan91** [comment]
@HuguesTHOMAS thank you.  and could you please give me some guidance for which part of code i should modify to implement your model for my own obj data?

**Comment by HuguesTHOMAS** [comment]
You have to create another dataset class. Just copy the `ModelNet40.py `file and rename it with your dataset name. Then you can change the functions in this file to adapt it to your dataset. In particular the point cloud files are loaded in the function named `load_subsampled_clouds`
