### ISSUE TITLE
Error occuring when trying to trian ModelNet40

### ISSUE THREAD

**Issue by edshkim98** [HuguesTHOMAS/KPConv-PyTorch#35]
Hi, thank you for sharing your code in Pytorch!
I was trying to run train_ModelNet40.py after **sh compile_wrappers.sh** which gives me **running build_ext** as an output.
Also, I get this error message below when I do python3 train_ModelNet40.py:
**....../KPConv-PyTorch/datasets/common.py", line 64, in grid_subsampling
    return cpp_subsampling.subsample(points,**
**AttributeError: module 'cpp_wrappers.cpp_subsampling.grid_subsampling' has no attribute 'subsample'**

Could you please give me an advice with this problem?
Thank you for your help in advance.

**Comment by edshkim98** [comment]
Hi, I have another question after reading through your paper and the code once again. I noticed that the radius and the subsampling grid size are measured in meters. I am a bit confused and does this mean I should not normalize my data before feeding into my model?
If so, is there anyway to choose the size of radius based on normalized data?

**Comment by HuguesTHOMAS** [comment]
For the first problem, it seems that you did not compiled the cpp wrappers correctly. I can't really help you without knowing your configuration, the exact output of `sh compile_wrappers.sh`, etc.

For your second question, it is just as you want to do it, you can either choose a radius and grid size adapted to the original data scale, or normalize the input and therefore adapt the radius and grid size. In the end it will be the same.

If you have normalized data, you can start with the parameters of ModelNet40. In this dataset, the objects are normalized too. Then you can try to modify the values if you want to experiment a little.

**Comment by edshkim98** [comment]
Thank you so much! Acutally, the cause of the first problem is that I accidentally git cloned your repository twice.
After deleting one of it got rid of that error.

**Comment by edshkim98** [comment]
Thank you for your reply! After re cloning your repository again and then do **sh compile_wrappers.sh**,
it creates a folder called **temp.linux-x86_64-3.6**. However, it still gives out the same error for training.
Does this seem to you that it has not correctly compiled?

**Comment by edshkim98** [comment]
Actually, i finally figured it out!
I have re cloned the repository again and followed the doc instruction and installed followings:
    sudo apt update
    sudo apt install python3-dev python3-pip python3-tk
Then, the problem is fixed.
