### ISSUE TITLE
Training with S3DIS dataset

### ISSUE THREAD

**Issue by yaping222** [HuguesTHOMAS/KPConv-PyTorch#4]
Hi, Hugues 
Thank you very much for your great codes. I have two questions on implementation with the S3DIS datasets.

1) I met the following error after 25 epochs:
 'RuntimeError: CUDA out of memory'
   I use 'batch_num = 3' and keep other parameters as the original code. 
   in_radius = 1.5,    num_kernel_points = 15,    first_subsampling_dl = 0.03,    conv_radius = 2.5, 
   deform_radius = 6.0,    KP_extent = 1.2,    KP_influence = 'linear',  aggregation_mode = 'sum',                  
   first_features_dim = 128,   in_features_dim = 5
   I'm using RTX2080ti and PyTorch1.5.0, Cuda10.1, cudnn7.6.3 
During the training, it takes about 10.7GB GPU memory. Before the 26th epoch, the error popped up. 
I wonder what is the possible reason for this error.

2) The loss during the training keeps fluctuating around 4 starting from the 3rd epoch. I cannot see obvious decrease in loss. 
e003-i0477 => L=5.083 acc= 63% / t(ms): 122.0 116.8 152.1)
e003-i0479 => L=4.044 acc= 78% / t(ms): 144.7 116.9 152.5)
e003-i0483 => L=4.744 acc= 62% / t(ms): 109.6 117.4 154.5)
e003-i0486 => L=4.503 acc= 77% / t(ms): 118.6 118.0 158.0)
e003-i0489 => L=4.099 acc= 71% / t(ms): 114.0 114.9 153.0)
e003-i0492 => L=4.226 acc= 74% / t(ms): 122.7 118.5 156.7)
e003-i0495 => L=4.434 acc= 71% / t(ms): 118.7 119.3 156.4)
e003-i0498 => L=3.956 acc= 87% / t(ms): 115.7 117.3 152.4)
...
e025-i0479 => L=4.096 acc= 76% / t(ms): 119.6 121.1 159.9)
e025-i0482 => L=3.515 acc= 85% / t(ms): 117.8 120.9 159.6)
e025-i0485 => L=3.297 acc= 91% / t(ms): 120.4 122.9 165.7)
e025-i0488 => L=4.218 acc= 74% / t(ms): 135.3 123.5 165.3)
e025-i0492 => L=4.084 acc= 67% / t(ms): 107.2 122.6 162.7)
e025-i0495 => L=4.135 acc= 75% / t(ms): 102.4 120.1 158.9)
e025-i0498 => L=3.695 acc= 81% / t(ms): 104.7 120.0 158.9)
Here are my learning parameters:
    epoch_steps = 500  
    validation_size = 200
    learning_rate = 1e-2
    momentum = 0.98
    lr_decays = {i: 0.1 ** (1 / 150) for i in range(1, max_epoch)}
    grad_clip_norm = 100.0
I wonder whether this change in loss is expected or the loss should decrease much faster?
I would be appreciated if you could share your training figure.

Best wishes,
Yaping

**Comment by HuguesTHOMAS** [comment]
Hi @yaping222,

 1. This error means that some input was too big and could not fit into your gpu. To avoid such a problem, you can try to reduce the `in_radius` or increase `first_subsampling_dl`. I dont recommend using a `batch_num` lower than 3 or 4.

 2. The absolute value of the loss is not really important as long as the loss decreases over time. In this case, the loss is high because it includes the regularization loss of the deformable convolutions. You can plot the loss values with `plot_convergence.py` and see that they are decreasing over time. (You can run this while the network is training without problems). 

Best,
Hugues

**Comment by HuguesTHOMAS** [comment]
By the way, you can also replace the deformable convolution by normal convolutions to reduce the memory consumption of the network.

**Comment by yaping222** [comment]
Hi, Hugues
Thank you very much for your reply.


> By the way, you can also replace the deformable convolution by normal convolutions to reduce the memory consumption of the network.

Yes, I change it to normal convolutions and the memory consumption is reduced. 

For the second question, when I use 'use_potentials=False', the loss is much smaller but it varies around 1 and I can't see the improvement in the validation dataset. 
Here is the mean IoU on the validation dataset during the training (when I set 'use_potentials=True'). It seems the mean IoU is reaching the plateau.
![image](https://user-images.githubusercontent.com/47004480/81609687-9c234e80-93d8-11ea-8a9f-10eba4090770.png)
So may I ask how many steps I should expect to get a model for S3DIS, like 10k steps or 100k steps?

Best wishes,
Yaping

**Comment by HuguesTHOMAS** [comment]
I usually wait for at least 200 or 300 epochs to see the network converging, each epoch consisting of around 1000 steps.

By the way, having a lower loss value does not mean you are going to have better scores. Sometimes it can even be the opposite. You can compare performances with use_potential = true or false and you will see that even if the loss has different values, the validation score are pretty similar.

**Comment by yaping222** [comment]
Hi, Hugues
Thank you very much for your comments.
Best wishes,
Yaping
