### ISSUE TITLE
bug when training S3DIS dataset in random mode instead of potential mode

### ISSUE THREAD

**Issue by zc-tx** [HuguesTHOMAS/KPConv-PyTorch#45]
Hi @HuguesTHOMAS ,
I am training S3DIS dataset in random mode instead of potential mode, if input_threads is set to 0, every thing is ok, but if input_threads is set to bigger than 0, this will lead to a crash.
My change is like this:
training_dataset = S3DISDataset(config, set='training', use_potentials=**False**)

Thanks!

**Comment by zc-tx** [comment]
Solved!

**Comment by PPPPeterpan** [comment]
Hi @zc-tx, may I ask how you solved this? get the same problem in random sample mode

**Comment by amirhszd** [comment]
@PPPPeterpan I also had the same problem. If you are passing a class 0 as unknown that is not in your data you should also denote it in ignored_labels, otherwise the random method gets stuck in a while loop! Hope this helps
