### ISSUE TITLE
How to build a data_loader for custom dataset?

### ISSUE THREAD

**Issue by luciaL** [HuguesTHOMAS/KPConv-PyTorch#46]
hello, thank you for your great work.
I noticed that you use complex data_loaders, which may be hard to understand but in the end are more efficient.
Now I'd like to train on my own dataset, Could you please give me some tips to  build a dataloader for my own dataset?

**Comment by HuguesTHOMAS** [comment]
Hi @luciaL,

Yes indeed, but it is not really possible to help you with simple general advice. There are so many details. I guess your best chance is to read about dataloaders on PyTorch official website and then try to follow the execution of my code to see what happens. 

Then if you face a particular issue when implementing your own dataset, you can ask me again, and I should be in a better position to help you.

Best,
Hugues

**Comment by luciaL** [comment]
Hi, Hugues,

Thank you so much for your reply. Your suggestion is very useful. I will read your code carefully and try to implement on my own dataset.
 
Best,
Lucia
