### ISSUE TITLE
Different batch size different results during the inference

### ISSUE THREAD

**Issue by fazzi1992** [HuguesTHOMAS/KPConv-PyTorch#47]
Hi, @HuguesTHOMAS,
I am trying to use your library on my own dataset.
My own dataset  is very huege and a single point cloud has dimension that can reach the 15 GB and I have some porblems related to the out of memory during the inference phase.
Hence, I have tried to modify the batch_size parameters from 1 to 200 in order to avoid the out of memory.
Unfornutely, changing the batc_size parameters I don not obtain good results in terms of IoU a
As double check, I have tried to classify a small points cloud (1 GB) with two value of the batch_size and i have obtain:

-  batch_size = 1 good performance

- batch_size = 200 poor performance

Do you have some ideas of how can I solve my problem?
Thank you,
Giovanni

**Comment by HuguesTHOMAS** [comment]
What do you mean by `batch_size = 200`?

Do you have 200 point clouds stacked together? In that case you should consume 200 times more memory than `batch_size = 1`, and you should also have better results... So what you are saying does not make much sense to me.

When you say batch_size, do you mean the `batch_num` parameter in my code? Do you also keep the same calibrations functions before training?

**Comment by fazzi1992** [comment]
Thank you for your response @HuguesTHOMAS. I am sorry if the explanation is unclear. 
When I speak about batch_size, I am referring to the batch_size of the DataLoader. Here, the snapshot of the code that I am trying to change:
`test_loader = DataLoader(test_dataset,
                             batch_size=1,
                             sampler=test_sampler,
                             collate_fn=collate_fn,
                             num_workers=10,
                             pin_memory=True)`

I have a single huge points cloud and I have problem related to the "out of memory". I have tried to change the batch_size in order to avoid the "out of memory issue".
Thank you,
Giovanni

**Comment by HuguesTHOMAS** [comment]
The batch size of the DataLoader does not control the effective size of a batch. It should always remain 1. If you change it, the network will not behave as expected. I am even surprised that this did not cause a crash. 

If you want to play with network parameters, it all happens in the Configuration class. If you have memory issues, try to reduce the `batch_num` parameter, the `in_radius` parameter, of increase the `first_subsampling_dl` parameter.
