### ISSUE TITLE
Why do you add the rotation during grid_subsampling? How can I avoid rotation augmentation?

### ISSUE THREAD

**Issue by mutianxu** [HuguesTHOMAS/KPConv-PyTorch#55]
Hi @HuguesTHOMAS ,

1. I noticed that you add the rotation, scaling and noise for data augmentation, and I'm trying to delete rotation augmentation for my own model. But I also notice that you add the rotation during grid_sampling at: https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/datasets/common.py#L118. Could you plz tell me why do you add the rotation during grid_subsampling?

2. (1) I also noticed you mentioned "add scale and rot for testing" at: https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/datasets/S3DIS.py#L431, but I could not find where you use this scale or rot for testing.
(2) Thus I think that if I want to avoid the rotation augmentation, the only thing I need to do is to avoid adding the rotation at: https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/datasets/common.py#L312. Is that right? 
(3) Do I need to also revise the code mentioned in 2(1) to avoid rot during testing? If that's the case, how can I revise it?

Thanks a lot for your help!

**Comment by HuguesTHOMAS** [comment]
Hi @mutianxu,

1. If you look a little bit further in the code, After I rotate and subsample the points, I realign them in there original pose:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/datasets/common.py#L134
Basically what I was trying to achieve here was to make the grid subsampling happening on a randomly oriented grid, to reduce the bias introduced by the fact that all points would always be subsampled with a unique grid. This is not a rotation augmentation as the shape eventually remains in the same pose, but the subsampled points can have different positions for the same shape, so it could be considered as a kind of noise augmentation. If you dont want it, you can set the parameter `random_grid_orient` to `False` when calling the `batch_grid_subsampling` function.

2. (1) I keep the rotation ans scale for sometimes when I have to debug things, it can be useful to see exactly what happened. Other than for debugging it is useless so you can drop it if you want

    (2) The most simple way to avoid rotation is to set the parameter `config.augment_rotation` to `'none'` or any other string other than `'vertical'` and `'all'`. You see here the rotation matrix is initialized as the identity
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/datasets/common.py#L255-L256

    And if the `config.augment_rotation` is set to `'none'`, then it will remain identity and the rotation augmentation will thus be eliminated.

    (3) As I said just use the `config.augment_rotation` parameter. For training you can set it in the configuration class directly and for testing you can set configuration parameters here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/test_models.py#L138-L149

**Comment by mutianxu** [comment]
@HuguesTHOMAS ,
Got it, thank you so much!
