### ISSUE TITLE
Problems with batch_num in pytorch version

### ISSUE THREAD

**Issue by 123zhen123** [HuguesTHOMAS/KPConv-PyTorch#56]
嗨，@HuguesTHOMAS,
I am trying to use your library in the SemanticKitti dataset.
I tried to modify the `batch_num` parameter from` 8` to `160` to make full use of computing resources.
Unfortunately, the following error is reported at line 801 of` SemanticKitti.py`:
```
self.dataset.epoch_inds += gen_indices
RuntimeError: The size of tensor a (35200) must match the size of tensor b (4071) at non-singleton dimension 0
```
I don’t know why there is such a problem when increasing batch_num, I can’t find a reasonable solution

**Comment by HuguesTHOMAS** [comment]
I need a little bit more information to know where the problem is. What line creates the error for example?

In the meantime you can look at this issue #42
