### ISSUE TITLE
About the Data Augmentation During Test

### ISSUE THREAD

**Issue by mutianxu** [HuguesTHOMAS/KPConv-PyTorch#58]
Hi @HuguesTHOMAS ,

Could you please tell me why do you add the same data augmentations used in training to test? (As the default code in test_models.py, if I do not specify the config, then all the data augmentations used in training will be added into test.)

Thanks a lot!

**Comment by HuguesTHOMAS** [comment]
> if I do not specify the config, then all the data augmentations used in training will be added into test

Yes indeed. It makes sense when you use a voting scheme to include some augmentation at training too. It can reduce the bias in the training set. Imagine for example that all the test clouds are oriented in a way that makes the network prediction very good,  adding rotation augmentation breaks this, and helps you know what your network is really able to do.

That being said it depends a lot on your data, your application, etc. You can always change the config parameters to meet your expectations.

**Comment by mutianxu** [comment]
Got it. Thanks for your reply.
