### ISSUE TITLE
About the final result of voting test on S3DIS

### ISSUE THREAD

**Issue by mutianxu** [HuguesTHOMAS/KPConv-PyTorch#59]
Hi @HuguesTHOMAS ,

When I run the test_models.py, the result we refer should be the result under 'confusion on full clouds'. 

However, due to such test is a **voting** test, do I need to calculate the **average** iou of all results under 'confusion on full clouds', so that to use this average result as the final result? 

Or, we just need to directly report the **max** iou among all results under 'confusion on full clouds' as the final result?

Thanks for your help!

**Comment by HuguesTHOMAS** [comment]
To be correct, you should report the last "confusion on full clouds" results. As we use a voting test, the predictions are already averaged as test_models.py runs. So the longer you wait the more votes are computed for each point and the better the confusion on full clouds should reflect your network performances. Usually, there are no big differences between "confusion on full clouds" after a few votes.

**Comment by mutianxu** [comment]
> To be correct, you should report the last "confusion on full clouds" results. As we use a voting test, the predictions are already averaged as test_models.py runs. So the longer you wait the more votes are computed for each point and the better the confusion on full clouds should reflect your network performances. Usually, there are no big differences between "confusion on full clouds" after a few votes.

Thank you very much.

If I understand correctly, we should wait for the **whole** test_model.py finished testing, so that the total voting times will all be same across different experiments for a fair comparison, making the last "confusion on full clouds" results are based on the same times of voting, right?

**Comment by HuguesTHOMAS** [comment]
Yes indeed. But you can change the number of votes when calling the function so that it does not take too long. 10 votes should be enough to get consistent results

**Comment by mutianxu** [comment]
> Yes indeed. But you can change the number of votes when calling the function so that it does not take too long. 10 votes should be enough to get consistent results

OK. Thanks a lot!
