### ISSUE TITLE
SemanticKitti all batches are unit sized

### ISSUE THREAD

**Issue by sgasperini** [HuguesTHOMAS/KPConv-PyTorch#6]
Hi,
thank you very much for making this PyTorch version available!
I wonder why at line 1230 of `SemanticKitty.py` (here: [https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/datasets/SemanticKitti.py#L1230](url)) you remove the batch size, and with that all the other input samples except for the first one in `input_list`, making all batches unit sized.
In fact, because of that, what goes into the network is always a single point cloud, no matter `config.batch_num`.
Could you please explain why?
Doesn't that alter the training process, reducing the number of iterations and missing most of the samples for each epoch?
Does that have to do with the parallelism introduced by `config.input_threads`, so each thread picks one? Debugging I probably can't see this happening. If so, the code doesn't work the same with multi-batch size and a single thread right?
Thank you!

**Comment by HuguesTHOMAS** [comment]
Hi @sgasperini,

We do not use a batch dimension but still have more than one single point cloud in a batch. Insterad, we stack all point clouds together. I invite you to read [this answer](https://github.com/HuguesTHOMAS/KPConv/issues/8#issuecomment-493909354) I previously gave on the originale tensorflow github, to understand how we handle the batch size.

Therefore the batch dimension is useless in our case, this is why we remove it at line 1230 of `SemanticKitty.py`.

I hope this clarifies your questions.
Best,
Hugues

**Comment by sgasperini** [comment]
Hi @HuguesTHOMAS,
thank you very much for your quick answer, very interesting!
Stay healthy,
Stefano
