### ISSUE TITLE
What is dataset.min_potentials? why do they decide when a test is complete?

### ISSUE THREAD

**Issue by Arjun-NA** [HuguesTHOMAS/KPConv-PyTorch#69]
Hi @HuguesTHOMAS ,

Thank you for the amazing support. I am stuck with the min potential not rising up like how it is in other datasets for my implementation on Dales Dataset. So, I would like to know what that is and what is the idea behind it so I can modify/adjust that variable.

Regards,
Arjun

**Comment by HuguesTHOMAS** [comment]
If you use potential for the picking strategy, the dataset sampler is going to choose the point with the lowest `potential` value. If you have different scenes, the sampler first needs to choose the scene containing the point with the lowest `potential` value. Therefore, we store the minimum value of potential for all scenes in the `min_potential` array.

There could be two reasons why the min potential is not rising. 

1) you don't update the `potential` array of a scene after you pick a point in it.
2) you update the `potential` but not the `min_potential`

If you need more details on the potential sampler, you can have a look at my [Ph.D. thesis, section IV.2.8.c page 127-128](https://pastel.archives-ouvertes.fr/tel-02458455/document)

**Comment by JihaoLee** [comment]
Hi, @HuguesTHOMAS,
I have some confusions about this picking strategy (useing potential). It may appear that only some areas are sampled, and some areas are not sampled. Do you think this understanding is correct?
I find that RandLA-Net also uses this picking strategy. In some previous methods, point clouds are split into small blocks. This split approach can cover all areas. What are the advantages of your strategy, compared with previous method?
Thank your in advance!

**Comment by HuguesTHOMAS** [comment]
> It may appear that only some areas are sampled

Actually, this is the exact opposite, the potential picking ensures that all areas are sampled equally. If an area is not sampled, then its potential remains low, while the rest rises, and therefore it should be sampled (as we pick the area with the lowest potential).

The problem of splitting into small blocks is that it reduces the diversity of data. With our potential strategy, every area is picked approximatively the same number of times, but the centers of the spheres remain quite random. The objects that are splitter at the border of the spheres are not always the same, as opposed to the block strategy.

**Comment by JihaoLee** [comment]
Sorry, area is an unclear expression. I mean that for an area, such as Area_2 in S3DIS, how to cover all point clouds in Area_2? Some point clouds in Area_2 may not be sampled. Of course, if the number of sample times is sufficient, it can cover all point clouds theoretically. How do you control the number of sampling times?

> The objects that are splitter at the border of the spheres are not always the same  

I don't understand it. I know the border of block strategy is unchannged. Is the border of the potential picking random?
Thank you very much!

**Comment by HuguesTHOMAS** [comment]
>  how to cover all point clouds in Area_2?

I think what you do not understand is that the potential strategy acts at the level of the points. each point of each area has potential, so we are ensured to cover all the points in all the areas. Look at figure 64 in my Ph.D. thesis (link above).

>  Is the border of the potential picking random?

Yes it is, the minimum of potential in a point cloud changes all the time, ensuring diversity.

**Comment by Arjun-NA** [comment]
Hi @HuguesTHOMAS ,

Thank you for the reply. I will check if that 2 conditions are happening. I actually meant that the min_potential for me is slowly rising, It is not fast and thus not savings potentials and thus no result.

On an another issue, I had some modifications in the layers and I would like to know
`L = (len(input_list) - 7) // 5` 
how is this layers calculated.

thanks,
Arjun

**Comment by JihaoLee** [comment]
@Arjun-NA 

> L = (len(input_list) - 7) // 5

You can refer to datasets/common.py line 570

        li = input_points + input_neighbors + input_pools + input_upsamples + input_stack_lengths
and datasets/S3DIS.py line 431

        input_list += [scales, rots, cloud_inds, point_inds, input_inds]

5 means 5 layers.

Hope it can help you!

**Comment by JihaoLee** [comment]
@HuguesTHOMAS 

Thank you very much!

**Comment by HuguesTHOMAS** [comment]
@Arjun-NA,

As @JihaoLee said, 5 is the number of layers, this is a bad implementation and I should modify it in the future to take into account different numbers of layers.

Best,
Hugues

**Comment by Arjun-NA** [comment]
Hi,

Thanks for the reply. Does the 7 mean the reconstruction layer?

Arjun.

**Comment by Arjun-NA** [comment]
Thank you for the reply.
