### ISSUE TITLE
Code for Part Segmentation in Pytorch

### ISSUE THREAD

**Issue by imankgoyal** [HuguesTHOMAS/KPConv-PyTorch#7]
Hi,

Thank you so much for open-sourcing your code. Awesome work! I was wondering if you are planning to release Pytorch code for the shapenet part dataset as well.

Best,
Ankit

**Comment by HuguesTHOMAS** [comment]
Hi @imankgoyal,

Thanks for your interest in the code. Adding ShapeNetPart is not is the plan right now, but if you need to use this dataset, you should be able to create a ShapeNetPart.py script, with the class for loading this dataset. You can use the Modelnet40.py and S3DIS.py scripts as inspiration.

Best,
Hugues

**Comment by imankgoyal** [comment]
Thanks for the response!

**Comment by densechen** [comment]
@imankgoyal Hi, do you rewrite the code for ShapeNetPart?

**Comment by imankgoyal** [comment]
Unfortunately I didn't write it.
