### ISSUE TITLE
Training on S3DIS - cannot train

### ISSUE THREAD

**Issue by SRAVANIDHARA** [HuguesTHOMAS/KPConv-PyTorch#71]
I am able to load the data, KDTrees are found but during training, I get a constant error and I am stuck please help.
![Capture1](https://user-images.githubusercontent.com/56831610/104845664-e0a3aa00-58d6-11eb-9acb-9e981891651a.PNG)
![Capture2](https://user-images.githubusercontent.com/56831610/104845665-e13c4080-58d6-11eb-849b-b41ec3349560.PNG)

**Comment by HuguesTHOMAS** [comment]
when the batch is created, try to convert the labels to np.int64 before calling the function from_numpy. You can do it here:

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/datasets/S3DIS.py#L1316
