### ISSUE TITLE
is there subtle difference on KPConv module from that of paper? 

### ISSUE THREAD

**Issue by ooodragon94** [HuguesTHOMAS/KPConv-PyTorch#73]
Hello!
first of all I deeply thank your code share

I do have one question regarding to the operation on KPConv
In paper, from what I know, it follows as...

1. subtract all neighboring points from a basis point
2. subtract that to kernel points
3. put the result to the linear correlation function "h"
4. multiply that with a learnable weight
5. multiply the output to other points (denoted as f_i in paper)

However I am uncertain with the process and think process 4 and 5 should be changed. This learnable weight will change the dimension of the data which will not allow the multiplication operation on 5

and that is what I see on the pytorch code

Is there something I am missing??

thanks in advance!

**Comment by HuguesTHOMAS** [comment]
Hi @ooodragon94,

In the paper, the convolution operation is defined by:
![image](https://user-images.githubusercontent.com/16581582/106179921-aa351d00-6169-11eb-83fb-5b48885a4ae0.png)
With
![image](https://user-images.githubusercontent.com/16581582/106179834-94bff300-6169-11eb-95d8-b9572a915886.png)

Even though I decided to separate the summation like this, the result remains a double summation over the number of neighbor points `i` and the number of kernel points `k`. The only term that depends on both `i` and `k` is the correlation, so we have to compute them first in any case. But after that, we can either multiply by the weights W(k) first and the features f(i) second, or vice versa. 

I separated the summations in the paper for a better comprehension of what happens, but the most optimal way to implement it is to multiply by f(i) first. In the end, the operation is strictly identical to what is described in the paper.

Best,
Hugues
