### ISSUE TITLE
About predicting

### ISSUE THREAD

**Issue by ghost** [HuguesTHOMAS/KPConv-PyTorch#74]
HI, @HuguesTHOMAS 
Thanks for the awesome work and open-sourcing the code.
Can you share the prediction code？The prediction output is obtained and the ply file is generated

**Comment by wangshihuang** [comment]
The existing code is too complex and I don't know how to extract it

**Comment by HuguesTHOMAS** [comment]
The prediction code is in [tester.py](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/utils/tester.py)
You can call it with the script [test_models.py](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/test_models.py).

I cannot make the code more simple, you will have to take time to understand it. I usually comment a lot in my implementations, I hope that it will help you.

Best,
Hugues

**Comment by wangshihuang** [comment]
Thank you very much.

Ask again

In cloud_ segmentation_ Test, why use a dead cycle to predict, what is the condition of jumping out, I observed last_ Min + 1 is always greater than new_ Min, I use s3dis data

**Comment by HuguesTHOMAS** [comment]
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/utils/tester.py#L460-L462

The loop is broken when last_min gets bigger than the fixed value num_votes
