### ISSUE TITLE
modelnet40 scale and norm

### ISSUE THREAD

**Issue by CarmiShimon** [HuguesTHOMAS/KPConv-PyTorch#76]
Hi HuguesTHOMAS, 
Thanks for sharing with us such a great work which could help us a lot with a research we're doing!

I'd like to combine objects from KITTI dataset and existing point clouds from ModelNet40. 
I wonder, how did you normalize and scale the point clouds? Is it spherical?
Additionally, is it necessary to have the normals in order to train the network or just x, y, and z?

Thanks a lot!
Carmi

**Comment by HuguesTHOMAS** [comment]
Hi @CarmiShimon,

I am not sure to understand your question. IF you are talking about the models from ModelNet40, I use the data from PointNet article, where all objects are already scaled to fit in a unit sphere. If you are talking about the input point cloud in the network, they are not normalized, I take the data as-is and the network convolutions are scaled accordingly with the subsampling size (`first_subsmpling_dl `in the code).

The network does not need normals, but it can use them if you want to.

Best,
Hugues
