### ISSUE TITLE
grid subsampling

### ISSUE THREAD

**Issue by tiger-bug** [HuguesTHOMAS/KPConv-PyTorch#81]
Good morning,

Thank you so much for your code and work.  I have used it in the TF version and am trying it in the PyTorch version.  I am running into an issue with the ```grid_subsampling``` code found in line 743 of the S3DIS code (or at least it's something similar.  I am doing this for a custom dataset.)  My dataset consists of ```x,y,z,r,g,b,label```, however r,g,b are just dummy variables (all set to 0).  This is just for the convenience of the code.  Upon training, I ran into the error message:

```RuntimeError: Error converting input features to numpy arrays of type float32```

```x,y,z,label``` are all float32, rgb are uint32.  I am not sure what the issue is.  I suspect something in the cpp code and how it is interacting with my dataset.  Regrettably C++ is not a particular strong suit of mine, so I cannot find it.  

Also a couple of things to note:

* I am using a docker image of pytorch from [nvidia](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch) with version 1.4.
     * Note: This version uses Anaconda 
* Operating System: Ubuntu 18.04.3 LTS

Thank you!

**Comment by HuguesTHOMAS** [comment]
Hi @tiger-bug,

The c++ code is very specific about the type of array you give to it. Points and features have to be float32, and labels (if they are encoding a class attribute) have to be int32. You don't have to go into the C++ code, just convert your values to the right type (color to float32 and labels to int32). You can add the conversion between the loading of the files and the call to the grid subsampling function here: 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/datasets/S3DIS.py#L736-L743

Best,
Hugues

**Comment by tiger-bug** [comment]
I apologize, I thought I had the points in the right format.  Silly mistake on my part.  I changed them to type32 explicitly right before subsampling and that fixed the issue.  Thank you for the response!
