### ISSUE TITLE
Bug on trainer.py

### ISSUE THREAD

**Issue by ZhengdiYu** [HuguesTHOMAS/KPConv-PyTorch#82]
Hey @HuguesTHOMAS ,

https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/utils/trainer.py#L432-L436

In the codes above the nc_tot and nc_model seem to be the same, which will lead to an exception of tensor size unmatch in the code below if the ignored label is not empty:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/utils/trainer.py#L501-L502

Should I move L527 ~ 530(below) before L501~502(above)? Or should I fix nc_tot and nc_model to what you said in the comment (fix nc_model to num_classes - num_ignored_classes)?
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/utils/trainer.py#L527-L530

Could you have a check? Thank you!

I think we could also change the code here:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/bb0ea445b168463d4b7dffee8b61c235775fc33a/datasets/S3DIS.py#L94
to config.num_classes = self.num_classes - len(self.ignored_labels)

Best,
Zhengdi

**Comment by HuguesTHOMAS** [comment]
Hi @ZhengdiYu,

You are right, I did not take care of that in the PyTorch implementation as I did not use it for datasets with ignored labels.

Your correction is the right one indeed, it has to be 

```
config.num_classes = self.num_classes - len(self.ignored_labels)
```

I just pushed this correction. As I am not working on this project currently, I would be glad if you could tell me here if the code runs well with this correction.

Thanks a lot,
Hugues
