### ISSUE TITLE
ques in Compile the C++ extension modules for python located in cpp_wrappers.

### ISSUE THREAD

**Issue by huixiancheng** [HuguesTHOMAS/KPConv-PyTorch#83]
Here are terminal result in pycharm
```
(sem) C:\Users\Aragaki Yui\Desktop\transformers\KPConv-PyTorch-master\cpp_wrappers\cpp_neighbors>build.bat
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
请按任意键继续. . .
```
I think it's fail to compile.

Enviroment:
Win10  Python==3.6  scikit-learn==0.24.1  numpy ==1.19.1
Compilers set as follow
![QQ截图20210302225815](https://user-images.githubusercontent.com/65054204/109667149-ceda4580-7baa-11eb-92dc-4a69c0e9c6ac.png)

Did I make mistakes？

**Comment by HuguesTHOMAS** [comment]
Hi @huixiancheng,

I don't know what the problem is here, but it seems that it comes from a python library missing indeed. Is your environment a virtual env or a docker? If yes, are you sure you were inside your environment when trying to compile the wrappers?

Best,
Hugues

**Comment by huixiancheng** [comment]
yes I use virtual env of conda and sure that i'm in this env.
Actually when firstly run build.bat,it's look like is working like follow but I doubt if it really worked
```
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'grid_subsampling' extension
creating build\temp.win-amd64-3.8
creating build\temp.win-amd64-3.8\cpp_utils
creating build\temp.win-amd64-3.8\cpp_utils\cloud
creating build\temp.win-amd64-3.8\Release
creating build\temp.win-amd64-3.8\Release\grid_subsampling
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Anoconda\lib\site-packages\numpy\core\include -IC:\Anoconda\include -IC:\Anoconda\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tp../cpp_utils/cloud/cloud.cpp /Fobuild\temp.win-amd64-3.8\Release\../cpp_utils/cloud/cloud.obj -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Anoconda\lib\site-packages\numpy\core\include -IC:\Anoconda\include -IC:\Anoconda\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpgrid_subsampling/grid_subsampling.cpp /Fobuild\temp.win-amd64-3.8\Release\grid_subsampling/grid_subsampling.obj -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Anoconda\lib\site-packages\numpy\core\include -IC:\Anoconda\include -IC:\Anoconda\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpwrapper.cpp /Fobuild\temp.win-amd64-3.8\Release\wrapper.obj -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Anoconda\libs /LIBPATH:C:\Anoconda\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 /EXPORT:PyInit_grid_subsampling build\temp.win-amd64-3.8\Release\../cpp_utils/cloud/cloud.obj build\temp.win-amd64-3.8\Release\grid_subsampling/grid_subsampling.obj build\temp.win-amd64-3.8\Release\wrapper.obj /OUT:C:\Users\Aragaki Yui\Desktop\transformers\KPConv-PyTorch-master\cpp_wrappers\cpp_subsampling\grid_subsampling.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\../cpp_utils/cloud\grid_subsampling.cp38-win_amd64.lib
请按任意键继续. . .
```

**Comment by HuguesTHOMAS** [comment]
Why do you doubt if it really worked? Did you try to run the code after this first build? Is there an error message?

Note that I tried the code on Windows only once to verify that it worked, but I mainly use Linux. You should use Linux if you still have problems with windows

**Comment by huixiancheng** [comment]
Will  It looks like I made a mistake and I will follow your advice. :see_no_evil: Thanks for your quick reply

**Comment by GeoSur** [comment]
> Will It looks like I made a mistake and I will follow your advice. 🙈 Thanks for your quick reply

Hello,did u run this code on windows successfully? I just run it on linux, and are u study point clouds too?

**Comment by huixiancheng** [comment]
sorry for long time pass, i miss the detail. In my memory, it could compile and train successfully in windows.

**Comment by GeoSur** [comment]
> 

Thanks! I finally run it in windows!

**Comment by Jaychouxq** [comment]
> 

are you chinese?

**Comment by Jaychouxq** [comment]
> 抱歉过了很久，我错过了细节。在我的记忆中，它可以在Windows中成功编译和训练。

are you chinese?

**Comment by UncleSan** [comment]
> 

Would you please post the way to solve this problem? Thanks！

**Comment by UncleSan** [comment]
> > 
> 
> Thanks! I finally run it in windows!

Would you please post the way to solve this problem? Thanks！

**Comment by GeoSur** [comment]
@UncleSan 
sure! You may change these two areas 

-Change '/' to '\\'  in trainer and tester

- May add a type transformer when the code produces "target type error"

**Comment by UncleSan** [comment]
@GeoSur Thank you for your reply. I mean how to compile the C++ extension modules for python located in cpp_wrappers in win10.  when I use the command "python setup.py build_ext --inplace" to compile the extension modules, some similar errors are shown, like

`
running build_ext
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
building 'radius_neighbors' extension
creating build
creating build\temp.win-amd64-3.8
creating build\temp.win-amd64-3.8\cpp_utils
creating build\temp.win-amd64-3.8\cpp_utils\cloud
creating build\temp.win-amd64-3.8\Release
creating build\temp.win-amd64-3.8\Release\neighbors
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\Software\Anaconda3\envs\kpconv\lib\site-packages\numpy\core\include -ID:\Software\Anaconda3\envs\kpconv\include -ID:\Software\Anaconda3\envs\kpconv\Include /EHsc /Tp../cpp_utils/cloud/cloud.cpp /Fobuild\temp.win-amd64-3.8\Release\../cpp_utils/cloud/cloud.obj -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
cloud.cpp
D:\F\NJT\Codes\GitClone\SUMS-Semantic-Urban-Mesh-Segmentation-public-main-5stars\competing_methods\my_KPConv\cpp_wrappers\cpp_utils\cloud\cloud.h(22): fatal error C1083: Could not open the file: #include <vector>: No such file or directory
error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\Hostx64\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\Software\Anaconda3\envs\kpconv\lib\site-packages\numpy\core\include -ID:\Software\Anaconda3\envs\kpconv\include -ID:\Software\Anaconda3\envs\kpconv\Include /EHsc /Tp../cpp_utils/cloud/cloud.cpp /Fobuild\temp.win-amd64-3.8\Release\../cpp_utils/cloud/cloud.obj -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0" failed with exit status 2`

Or, could you please share the compiled results?
Thanks again.

**Comment by UncleSan** [comment]
@GeoSur I will try this method. Thank you!

**Comment by hongzhiqiang67** [comment]
> > 
> 
> Thanks! I finally run it in windows!

Please help me how much, thank you very much, my QQ3454136228

**Comment by GeoSur** [comment]
@hongzhiqiang67 看一下你的报错，是不是C++编译出了问题？
