### ISSUE TITLE
RuntimeError: Error

### ISSUE THREAD

**Issue by xinge008** [HuguesTHOMAS/KPConv-PyTorch#84]
Hi, @HuguesTHOMAS

When I run the batch_neightbors https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/94b1d87e17ec339e2aad049ce5d5d175b9cd0db1/datasets/common.py#L185-L196,

an error named "RuntimeError: Error" is appeared without more detailed information, in which `queries` is with shape (20000, 3) and 'supports' with shape (15000, 3). In fact, I can not reproduce this problem steadily and it seems sort of random.
Is there any hint about this issue?

**Comment by xinge008** [comment]
I also find that larger radius could significantly reduce this error (however, it also slows the speed). Maybe it is related to the empty neighbors?

**Comment by xinge008** [comment]
I got the point. :)

**Comment by cppcute-pm** [comment]
> I got the point. :)

Hello, @xinge008 . 
I have encountered the same issue and I'm wondering whether it's caused by some incorrect enviroments or it only require some specific setting about the radius or the point number.
