### ISSUE TITLE
Testing model on unseen/unlabeled data

### ISSUE THREAD

**Issue by divyasingh217** [HuguesTHOMAS/KPConv-PyTorch#85]
Hi @HuguesTHOMAS , Hope you are doing well.

I had one question regarding model prediction on unseen/unlabeled data.  Like you have mentioned the validation part in the code in which the data is already labeled but what about, if I want to get predictions on complete unseen data which is not labeled.

**Comment by HuguesTHOMAS** [comment]
Hi @divyasingh217,

You can use the test code for that: `test_models.py`, which calls functions in `utils/tester.py`. You might need some adjustments in tester.py to adapt it to your data, but nothing very complex.

Best,
Hugues
