### ISSUE TITLE
Could the network be tested with a different dowsample voxel size?

### ISSUE THREAD

**Issue by ZhengdiYu** [HuguesTHOMAS/KPConv-PyTorch#86]
Hey @HuguesTHOMAS 

I have noticed that you mentioned the model can be tested with a different first_subsampling_dl here:

https://github.com/HuguesTHOMAS/KPConv/issues/41#issuecomment-552904287

I followed what you said and add this code below in trainer.py:
```
        ##########################
        # Load previous checkpoint
        ##########################

        if (chkp_path is not None):
            if finetune:
                checkpoint = torch.load(chkp_path)
                net.load_state_dict(checkpoint['model_state_dict'])
                net.train()
                print("Model restored and ready for finetuning.")
            else:
                checkpoint = torch.load(chkp_path)
                net.load_state_dict(checkpoint['model_state_dict'])
                self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
                self.epoch = checkpoint['epoch']
                net.train()
                # for name, param in net.named_parameters():
                #     if 'kernel_points' in name:
                #         param *= (0.3/0.06)
                print("Model and training state restored.")

```
1. I have trained on KITTI with first_subsampling_dl=0.06 and I tried to do validation with first_subsampling_dl=0.3 on KITTI. 
So I just load the model trained with first_subsampling_dl=0.06 in train_SemanticKitti.py and change `trainer.train()` to `trainer.validation()` to have a quick test. But It just didn't work, the IoU is quite low. Did I miss something? (I just change the first_subsampling_dl to 0.3 and rescale the kernel_points like above).

2. In this issue: https://github.com/HuguesTHOMAS/KPConv-PyTorch/issues/8#issuecomment-634048230
You commented we could train a new network with different first_subsampling_dl. Does that mean the "rescale" strategy above is not the case for KITTI?

BTW:
After fixing the ignore_label bug, the code runs well now. Although there are still some problems with neighbour_limit dict or batch_limit dict or KDTree, will get back to you when I figure it out.

Best,
Zhengdi

**Comment by HuguesTHOMAS** [comment]
Hi @ZhengdiYu,

Training and testing with different subsampling sizes is not very wise. Think of it that way, the convolutions are small spatial filters trained to detect details in the shapes. If you train your network to detect details at a scale of X, it will be fit to "see" specific details of the shapes (let's say wheels on a car). Then when you test with a scale of 5X, your "wheels detectors" will try to find wheels that are 5 times bigger than before. Unless you train on cars and want to detect monster trucks, this will never work.

A solution would be to train your network to be robust to scale, by training with scale augmentation. I did some tests in the beginning and found that strategy to decrease the performances. The diversity of shape for the same object becomes a lot bigger and therefore is harder to learn.

**Comment by ZhengdiYu** [comment]
Hey @HuguesTHOMAS 

Thank you for your reply. It makes sense. 

But when will the "rescale strategy" you commented before work? If the two subsampling sizes are used for different scenes. Just like D3Feat. They use your KPConv to train on 3DMatch and test on ETH to test generalization ability. The two scenes have different subsampling sizes but one is indoor while the other one is outdoor scene. Is this a bit like your example of detecting from cars to trucks?

Or is it different for segmentation task? Is my implementation for "rescale strategy" correct?

**Comment by HuguesTHOMAS** [comment]
Hi @ZhengdiYu,

I think your implementation should work, but I might forget some details... To be absolutely sure, the best way would be to rescale the input point clouds instead of the network itself. Just load the network as is, and then when you feed your input, you can scale it (you have to do it before the first subsampling to ensure a consistent density of points between training and test)

About the example you give, yes, I think there are some specific applications where a rescale is relevant, but you can see it as an input rescaling instead of a network rescaling. Therefore you are trying to adapt some data to a network that was trained on another dataset. With the rescale, you make your data look more like the original training set. That being said, I still believe the results would be better if you train and test on the same dataset/environment (when it is possible).

Best,
Hugues
