### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Data/S3DIS/Area_1'

### ISSUE THREAD

**Issue by lllmmmwww** [HuguesTHOMAS/KPConv-PyTorch#91]
hello，Thanks for your work. When I run the tarin_S3DIS.py，It has the following errors “FileNotFoundError: [Errno 2] No such file or directory: '/Data/S3DIS/Area_1'” But I have downloaded the dataset and saved it in the specified location.

**Comment by lllmmmwww** [comment]
![image](https://user-images.githubusercontent.com/76770282/112795983-e5859680-909b-11eb-923a-96c7c6f879a3.png)

**Comment by HuguesTHOMAS** [comment]
Hi @lllmmmwww,

What is the path specified in your `dataset/S3DIS.py`? Here: 
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/7fefb6a8d38fd304775199777ad01d9f1546e2ff/datasets/S3DIS.py#L87-L88

Just verify it corresponds to the right path of your own data.

**Comment by lllmmmwww** [comment]
Hi @HuguesTHOMAS ,
Thank you for your reply. I have fixed this problem because my dataset folder has permissions set so that it can't be read properly.
