### ISSUE TITLE
Questions about adding multiple features

### ISSUE THREAD

**Issue by WJX0108** [HuguesTHOMAS/KPConv-PyTorch#93]
Dear Mr Thomas:
Hello!
I've been reading your paper for some time.I am currently using KPConv processing a large outdoor airborne LiDAR point cloud data (only contain position information and the label) classification problem, in order to get higher classification accuracy, I constructed some useful information, but your code can only be 1,4,7 input characteristics, I want to know if I have not input characteristics of these dimensions, what should I do?In addition, after I visualized the batch. features, I found that it is a matrix composed of 0 and 1, which I don't quite understand.Hope to get your answer.
Wish a happy life, smooth work!

**Comment by HuguesTHOMAS** [comment]
Hi @WJX0108,

If you have specific features, you have to modify the getitem function of the dataset. Specifically, you need to go there: https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/7fefb6a8d38fd304775199777ad01d9f1546e2ff/datasets/S3DIS.py#L402-L411

Here you can modify the `elif` statements to use your own features. Let's say you have no colors but two custom features, then you need to add these line (remember to always keep one column of features equal to 1):
```
 elif self.config.in_features_dim == 3: 
     stacked_features = np.hstack((stacked_features, features[:, :2])) 
```

This will work if, earlier in the file, you save your features in the features list called `f_list`:
https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/7fefb6a8d38fd304775199777ad01d9f1546e2ff/datasets/S3DIS.py#L366-L369

**Comment by WJX0108** [comment]
Thank you for your generous answer!I have a general idea what you mean.
In addition, I have a few more questions to ask you:
(1) The data I used is class unbalanced. As you said before, one of the ways to solve class imbalance in KPConv is to use the option use_superior =False when creating an ISPRSDataSet.I don't understand this, and I've tried to do it, but it doesn't work very well.
(2) I'm still not sure about the batch. features are matrices composed of 0 and 1.In my opinion, the first column of batch.features is 1, and the last three columns should be the data intensity or RGB characteristics.I don't know if I understand right?

**Comment by HuguesTHOMAS** [comment]
(1) Class unbalance is solved by the sphere sampling strategy. For one epoch we pick N/C spheres for each class where N is the number of spheres needed and C the number of class. This behavior is triggered by the parameter `use_potentials=False` in the S3DIS dataset.

(2) Your understanding is correct, the features should not be only binary values. You should check the values and the type of the arrays that contain the features at different lines in the getitem function
