### ISSUE TITLE
How to visualize the conv feature like Fig.6 and Fig.7?

### ISSUE THREAD

**Issue by hjxwhy** [HuguesTHOMAS/KPConv-PyTorch#97]
Hi Hugues,
I want to visualize the layer feature in your paper such as Fig.6 and Fig.7, Can you share your code on how to visualize it. Thank you so much!

**Comment by HuguesTHOMAS** [comment]
Hi @hjxwhy,

The visualization tools were implemented in the original version of KPConv in Tensorflow. I did not have time to implement them for this PyTorch version. You can have a look at the TensorFlow implementation and try to adapt it for PyTorch. Showing the features of one layer like Fig 6 is pretty straightforward. For the ERF, it could be more tricky.

Best,
Hugues

**Comment by hjxwhy** [comment]
ok, @HuguesTHOMAS  thanks for your reply!
